# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.chat_messages import ChatMessages
from .raw_client import AsyncRawV2Client, RawV2Client
from .types.v2chat_response import V2ChatResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class V2Client:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawV2Client(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawV2Client:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawV2Client
        """
        return self._raw_client

    def chat(
        self,
        *,
        model: str,
        messages: ChatMessages,
        max_tokens: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V2ChatResponse:
        """
        Generates a text response to a user message and streams it down, token by token.

        Examples
        --------
        from cohere import Client, UserChatMessageV2

        client = Client(
            client_name="YOUR_CLIENT_NAME",
            token="YOUR_TOKEN",
        )
        client.v2.chat(
            model="command-a-plus-05-2026",
            messages=[
                UserChatMessageV2(
                    content="Tell me about LLMs",
                )
            ],
        )
        """
        _response = self._raw_client.chat(
            model=model,
            messages=messages,
            max_tokens=max_tokens,
            request_options=request_options,
        )
        return _response.data


class AsyncV2Client:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawV2Client(client_wrapper=client_wrapper)

    async def chat(
        self,
        *,
        model: str,
        messages: ChatMessages,
        max_tokens: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> V2ChatResponse:
        """
        Generates a text response to a user message and streams it down, token by token.
        """
        _response = await self._raw_client.chat(
            model=model,
            messages=messages,
            max_tokens=max_tokens,
            request_options=request_options,
        )
        return _response.data
