// Code generated by scripts/sync-versions.mts from packages/runtime/package.json. DO NOT EDIT.

package invariant

// Version is the runtime version this engine implements, which a program's
// minRuntime is compared against.
const Version = "0.5.0"
