/**
 * The documentation is written once, in `docs/`, and read three ways: in the
 * repository, by the completeness test that keeps it honest, and here. This
 * copies it into the site rather than duplicating it, so there is never a
 * second copy for the two to disagree about.
 *
 * Two things are rewritten on the way: a Markdown file gains the front matter
 * Starlight needs, taken from its own first heading, and a link to another
 * `.md` file becomes a link to that page's address. Nothing else is touched,
 * so what a reader sees on the site is what a reader sees in the repository.
 */
import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";

const HERE = import.meta.dirname;
const ROOT = resolve(HERE, "..", "..");
const FROM = join(ROOT, "docs");
const INTO = join(HERE, "..", "src", "content", "docs");

/** Pages that are the repository's own scaffolding rather than documentation. */
const SKIP = new Set(["README.md", "docs.test.ts", "brief", "DESIGN.md"]);

/** The first `# heading` of a page, which is its title everywhere else. */
function titleOf(text: string, fallback: string): string {
  const heading = /^#\s+(.+)$/m.exec(text);
  return (heading?.[1] ?? fallback).replace(/`/g, "");
}

/** The sentence under the title, for the page's description. */
function describe(text: string): string | undefined {
  const body = text.replace(/^#\s+.+$/m, "").trimStart();
  const paragraph = body.split("\n\n")[0]?.replace(/\s+/g, " ").trim();
  if (!paragraph || paragraph.startsWith("#") || paragraph.startsWith("|")) {
    return undefined;
  }
  const sentence = /^(.+?[.!?])(\s|$)/.exec(paragraph)?.[1] ?? paragraph;
  return sentence.length > 160 ? undefined : sentence.replace(/[`*]/g, "");
}

/**
 * A link to another page of the documentation, as an address on the site:
 * `../reference/cli.md` beside `adapters/hono.md` is `/reference/cli`. A link
 * to anything else, including a file in the repository that is not
 * documentation, is left exactly as it was written.
 */
function withSiteLinks(text: string, page: string): string {
  return text.replace(/\]\(([^)]+?\.md)(#[^)]*)?\)/g, (whole, target: string, hash) => {
    const from = dirname(page);
    const resolved = relative(FROM, resolve(FROM, from, target)).replaceAll("\\", "/");
    if (resolved.startsWith("..")) return whole;
    const slug = resolved.replace(/\.md$/, "").replace(/(^|\/)README$/, "");
    return `](/${slug}${hash ?? ""})`;
  });
}

async function pagesIn(directory: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(join(FROM, directory === "" ? "." : directory), {
    withFileTypes: true,
  });
  const found: string[] = [];
  for (const entry of entries) {
    if (SKIP.has(entry.name)) continue;
    const path = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) found.push(...(await pagesIn(path, path)));
    else if (entry.name.endsWith(".md")) found.push(path);
  }
  return found;
}

await rm(INTO, { recursive: true, force: true });
await mkdir(INTO, { recursive: true });

const pages = await pagesIn("");
for (const page of pages) {
  const text = await readFile(join(FROM, page), "utf8");
  const title = titleOf(text, page.replace(/\.md$/, ""));
  const description = describe(text);
  const front = [
    "---",
    `title: ${JSON.stringify(title)}`,
    ...(description ? [`description: ${JSON.stringify(description)}`] : []),
    "---",
    "",
  ].join("\n");
  // The first heading becomes the page's title, which the site prints above
  // the body, so leaving it in the body would print it twice.
  const body = text.replace(/^#\s+.+\n+/, "");
  const target = join(INTO, page);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, front + withSiteLinks(body, page));
}

/**
 * The scoreboard is the evidence page: generated by the proving ground, read
 * here, never written by hand. Its table has four wide columns of prose,
 * which is right for a file and unreadable on a phone, so each line becomes a
 * section of its own: the claim, whether it is met, the number, and what
 * measured it.
 */
const scoreboard = await readFile(join(ROOT, "proving", "SCOREBOARD.md"), "utf8");
const rows = [...scoreboard.matchAll(/^\|\s*(L\d+b?)\s*\|(.+)$/gm)].map((match) => {
  const cells = (match[2] ?? "").split(" | ").map((cell) => cell.trim());
  return {
    line: match[1] as string,
    claim: cells[0] ?? "",
    status: cells[1] ?? "",
    value: cells[2] ?? "",
    evidence: (cells[3] ?? "").replace(/\|$/, "").trim(),
  };
});
const met = rows.filter((row) => row.status === "met").length;
await writeFile(
  join(INTO, "evidence.md"),
  [
    "---",
    'title: "Evidence"',
    'description: "Every claim this product makes, what measures it, and what is not met yet."',
    "---",
    "",
    "Every line of the launch gate, and what measures it. This page is generated",
    "by the proving ground and regenerated every night, so a line that is not met",
    "says so here before it says so anywhere else.",
    "",
    `**${met} of ${rows.length} met.**`,
    "",
    ...rows.flatMap((row) => [
      `## ${row.line}. ${row.claim}`,
      "",
      `**${row.status === "met" ? "Met" : row.status === "not met" ? "Not met" : "Not measured"}.** ${row.value}`,
      "",
      ...(row.evidence ? [`*Measured by:* ${row.evidence}`, ""] : []),
    ]),
  ].join("\n"),
);

const security = await readFile(join(ROOT, "SECURITY.md"), "utf8");
await writeFile(
  join(INTO, "security.md"),
  ["---", 'title: "Security"', "---", "", security.replace(/^#\s+.+\n/, "")].join("\n"),
);

await cp(join(ROOT, "LICENSE"), join(HERE, "..", "public", "LICENSE.txt"));
process.stdout.write(`${pages.length + 2} pages\n`);
