/**
 * Which code generator wrote a release, from what the release itself ships.
 *
 * Every marker here was read in a published artifact, not in a generator's
 * repository: a generator's configuration directory (`.openapi-generator/`,
 * `.speakeasy/`, Stainless's `.stats.yml`) usually stays behind in the SDK's
 * repository, and the header each generated file starts with is what an npm
 * tarball, a wheel or a module zip actually carries.
 */
import {
  closeSync,
  existsSync,
  openSync,
  readdirSync,
  readFileSync,
  readSync,
} from "node:fs";
import { join } from "node:path";
import { filesUnder } from "./read/files.ts";
import type { CallSite, Declaration, GeneratorId, Language } from "./types.ts";

const SOURCES: Record<Language, RegExp> = {
  typescript: /\.(?:[cm]?js|d\.[cm]?ts|ts)$/,
  python: /\.py$/,
  go: /\.go$/,
};

/**
 * The first bytes of a file, where a generated header is. openapi-generator
 * puts the API's whole description in each file's docstring before its own
 * name, so the head is a few kilobytes, not a line.
 */
function headOf(path: string, bytes = 8192): string {
  let fd: number | undefined;
  try {
    fd = openSync(path, "r");
    const buffer = Buffer.alloc(bytes);
    const read = readSync(fd, buffer, 0, bytes, 0);
    return buffer.subarray(0, read).toString("utf8");
  } catch {
    return "";
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

const HEADERS: [GeneratorId, RegExp][] = [
  ["stainless", /generated from our OpenAPI spec by Stainless/i],
  // Stripe's generator writes the same words without Stainless's name.
  ["stripe", /File generated from our OpenAPI spec(?!\s+by\s+Stainless)/i],
  ["speakeasy", /Code generated by Speakeasy/i],
  ["fern", /auto-generated by Fern/i],
  ["openapi-generator", /OpenAPI Generator|openapi-generator\.tech/i],
  ["openapi-typescript", /auto-generated by openapi-typescript/i],
];

const MARKERS: [GeneratorId, string][] = [
  ["openapi-generator", ".openapi-generator/VERSION"],
  ["openapi-generator", ".openapi-generator/FILES"],
  ["speakeasy", ".speakeasy/gen.lock"],
  ["fern", ".fern/metadata.json"],
  ["stainless", ".stats.yml"],
  ["stripe", "OPENAPI_VERSION"],
];

/**
 * The generators a release's files name, in a stable order. Reading every
 * file's head is cheap next to parsing it, and a release can hold the
 * output of more than one (Stripe's SDKs hand-write their core).
 */
export function detectGenerators(root: string, language: Language): GeneratorId[] {
  const found = new Set<GeneratorId>();
  for (const [generator, marker] of MARKERS) {
    if (existsSync(join(root, marker))) found.add(generator);
  }
  const files = filesUnder(root, (name) => SOURCES[language].test(name));
  // Enough files to see each generator's header, never the whole of a large one.
  const step = Math.max(1, Math.floor(files.length / 400));
  for (let index = 0; index < files.length; index += step) {
    const head = headOf(join(root, files[index] as string));
    for (const [generator, pattern] of HEADERS) {
      if (!found.has(generator) && pattern.test(head)) found.add(generator);
    }
  }
  // Stainless's header contains Stripe's words; only one of them wrote it.
  if (found.has("stainless")) found.delete("stripe");
  return [...found].sort();
}

/**
 * The endpoints a release's own documentation pairs with its methods.
 *
 * Stainless ships `api.md` in a Go module, a line per method: `<code
 * title="get /v1/messages/batches/{message_batch_id}">` and a link to
 * `#MessageBatchService.Get`. openapi-generator ships a table in its README,
 * `*IdentityApi* | [**deleteIdentity**](...) | **DELETE** /admin/identities/{id}`,
 * in an npm package, a Go module, and a wheel's `METADATA`. Both name the
 * method by its class alone, so each entry is held against the calls the
 * code makes and takes that method's full name from there: documentation
 * confirms what the code says, and never stands in for a method the code
 * does not have, with one exception. Stainless's link is to the Go type
 * itself, which is the name.
 */
export function documentedCalls(
  root: string,
  language: Language,
  code: readonly CallSite[],
): CallSite[] {
  const out: CallSite[] = [];
  const confirm = (
    type: string,
    method: string,
    verb: string,
    path: string,
    pkg?: string,
  ) => {
    const matching = code.find(
      (call) =>
        call.method === method &&
        (call.type === type ||
          call.type.endsWith(`.${type}`) ||
          call.type === `${type}Service`) &&
        (pkg === undefined || (call.package ?? "") === pkg),
    );
    if (matching) {
      out.push({ ...matching, verb, path, declared: true });
    } else if (pkg !== undefined) {
      out.push({
        type,
        method,
        verb,
        path,
        package: pkg,
        file: "api.md",
        declared: true,
      });
    }
  };
  const api = join(root, "api.md");
  if (language === "go" && existsSync(api)) {
    const module = existsSync(join(root, "go.mod"))
      ? /^module\s+(\S+)/m.exec(readFileSync(join(root, "go.mod"), "utf8"))?.[1]
      : undefined;
    for (const match of readFileSync(api, "utf8").matchAll(
      /<code title="(\w+) ([^"]+)">(.*?)<\/code>/g,
    )) {
      const link = /href="https:\/\/pkg\.go\.dev\/([^"#]+)#(\w+)\.(\w+)"/.exec(
        match[3] as string,
      );
      if (!link || !module) continue;
      const where = link[1] as string;
      if (where !== module && !where.startsWith(`${module}/`)) continue;
      const pkg = where === module ? "" : where.slice(module.length + 1);
      confirm(
        link[2] as string,
        link[3] as string,
        (match[1] as string).toLowerCase(),
        match[2] as string,
        pkg,
      );
    }
  }
  const readmes = [join(root, "README.md")];
  if (language === "python" && existsSync(root)) {
    for (const entry of readdirSync(root)) {
      if (entry.endsWith(".dist-info")) readmes.push(join(root, entry, "METADATA"));
    }
  }
  for (const readme of readmes) {
    if (!existsSync(readme)) continue;
    for (const match of readFileSync(readme, "utf8").matchAll(
      /^\s*\*(\w+)\*\s*\|\s*\[\*\*(\w+)\*\*\]\([^)]*\)\s*\|\s*\*\*(\w+)\*\*\s+(\S+)/gm,
    )) {
      confirm(
        match[1] as string,
        match[2] as string,
        (match[3] as string).toLowerCase(),
        match[4] as string,
      );
    }
  }
  return out;
}

/**
 * stripe-node from 22 compiles each namespace's types from their own
 * directory, `resources/Checkout/Sessions.ts`, and re-exports them as
 * `Stripe.Checkout.Session`. Each file's declarations are top-level in their
 * module, where a `Session` in `Checkout/` and one in `BillingPortal/` look
 * alike, so each is named through its directory, as before 22 the
 * declarations named themselves: `Checkout.Session`.
 */
export function stripeDirectoryNamespaces(
  declarations: Declaration[],
  calls: CallSite[],
): void {
  const prefixOf = (file: string) =>
    /(?:^|\/)resources\/((?:[^/]+\/)+)[^/]+$/
      .exec(file)?.[1]
      ?.split("/")
      .filter(Boolean)
      .join(".");
  // A file whose declarations already sit in their namespace, as
  // `V2/Billing/MeterEventStream.ts` declaring `namespace V2.Billing`, is
  // named by them.
  const within = (prefix: string, name: string) =>
    name === prefix || name.startsWith(`${prefix}.`) ? name : `${prefix}.${name}`;
  const renamed = new Map<string, string>();
  for (const each of declarations) {
    const prefix = prefixOf(each.file);
    if (!prefix) continue;
    const qualified = within(prefix, each.qualified);
    renamed.set(`${each.file}\u0000${each.qualified}`, qualified);
    each.qualified = qualified;
    if (each.parent) each.parent = within(prefix, each.parent);
  }
  const resolved = (each: Declaration, name: string) =>
    renamed.get(`${each.file}\u0000${name}`) ?? name;
  // stripe-node 22.0 to 22.1 declares `interface Session` at the top of the
  // file and its nested types in `namespace Checkout { namespace Session }`
  // beside it, which the reader could not join: named, they are one type
  // and the types nested in it.
  const types = new Set(
    declarations
      .filter((each) => each.kind === "object" && prefixOf(each.file))
      .map((each) => `${each.file}\u0000${each.qualified}`),
  );
  for (const each of declarations) {
    if (each.extends) each.extends = each.extends.map((base) => resolved(each, base));
    if (each.variants) each.variants = each.variants.map((name) => resolved(each, name));
    const dot = each.qualified.lastIndexOf(".");
    const container = dot > 0 ? each.qualified.slice(0, dot) : "";
    if (
      !each.parent &&
      prefixOf(each.file) &&
      container !== "" &&
      types.has(`${each.file}\u0000${container}`)
    ) {
      each.parent = container;
    }
  }
  for (const each of calls) {
    const prefix = prefixOf(each.file);
    if (prefix && !each.declared) each.type = within(prefix, each.type);
  }
}

/**
 * stripe-node before 22 declares each method as data rather than code, in
 * its resource files: `retrieveUpcoming: stripeMethod({ method: 'GET',
 * fullPath: '/v1/invoices/upcoming' })` in `resources/Invoices.js` is
 * `Stripe.InvoicesResource.retrieveUpcoming`, and one in
 * `resources/Checkout/Sessions.js` is on `Stripe.Checkout.SessionsResource`,
 * as its declarations name them. From 22 the methods are code, and the
 * generic reading of each method's body finds them.
 */
export function stripeDeclaredCalls(root: string, namespace?: string): CallSite[] {
  const calls: CallSite[] = [];
  const base = ["cjs/resources", "lib/resources", "esm/resources"].find((dir) =>
    existsSync(join(root, dir)),
  );
  if (!base) return calls;
  const pattern =
    /(\w+):\s*stripeMethod\(\{\s*method:\s*'(\w+)',\s*fullPath:\s*'([^']+)'/g;
  for (const file of filesUnder(join(root, base), (name) => name.endsWith(".js"))) {
    const parts = file.split("/");
    const resource = `${(parts.at(-1) as string).slice(0, -3)}Resource`;
    const type = [
      ...(namespace ? [namespace] : []),
      ...parts.slice(0, -1),
      resource,
    ].join(".");
    const text = headOf(join(root, base, file), 1024 * 1024);
    for (const match of text.matchAll(pattern)) {
      calls.push({
        type,
        method: match[1] as string,
        verb: (match[2] as string).toLowerCase(),
        path: match[3] as string,
        file: `${base}/${file}`,
        declared: true,
      });
    }
  }
  return calls;
}
