"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e0e8dad92725

from typing import Any, TYPE_CHECKING

from mistralai.client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .chatcompletionresponse import (
        ChatCompletionResponse,
        ChatCompletionResponseTypedDict,
    )
    from .usageinfo import UsageInfo, UsageInfoTypedDict

__all__ = [
    "ChatCompletionResponse",
    "ChatCompletionResponseTypedDict",
    "UsageInfo",
    "UsageInfoTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "ChatCompletionResponse": ".chatcompletionresponse",
    "ChatCompletionResponseTypedDict": ".chatcompletionresponse",
    "UsageInfo": ".usageinfo",
    "UsageInfoTypedDict": ".usageinfo",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
