"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 54adb9a3af16

from __future__ import annotations
from mistralai.client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import ConfigDict, model_serializer
from typing import Any, Dict, Optional
from typing_extensions import NotRequired, TypedDict


class UsageInfoTypedDict(TypedDict):
    prompt_tokens: NotRequired[int]
    completion_tokens: NotRequired[int]
    total_tokens: NotRequired[int]
    prompt_audio_seconds: NotRequired[Nullable[int]]
    service_tier: NotRequired[Nullable[str]]
    r"""The service tier at which the request was processed: standard or priority."""


class UsageInfo(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True, arbitrary_types_allowed=True, extra="allow"
    )
    __pydantic_extra__: Dict[str, Any] = pydantic.Field(init=False)

    prompt_tokens: Optional[int] = 0

    completion_tokens: Optional[int] = 0

    total_tokens: Optional[int] = 0

    prompt_audio_seconds: OptionalNullable[int] = UNSET

    service_tier: OptionalNullable[str] = UNSET
    r"""The service tier at which the request was processed: standard or priority."""

    @property
    def additional_properties(self):
        return self.__pydantic_extra__
