// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package anthropic

import (
	"context"
	"fmt"
	"net/http"
	"slices"

	"github.com/anthropics/anthropic-sdk-go/internal/requestconfig"
	"github.com/anthropics/anthropic-sdk-go/option"
	"github.com/anthropics/anthropic-sdk-go/packages/param"
	"github.com/anthropics/anthropic-sdk-go/packages/respjson"
	"github.com/anthropics/anthropic-sdk-go/shared/constant"
)

// MessageService contains methods and other services that help with interacting
// with the anthropic API.
type MessageService struct {
	Options []option.RequestOption
	Batches MessageBatchService
}

// Send a structured list of input messages with text and/or image content, and the
// model will generate the next message in the conversation.
func (r *MessageService) New(ctx context.Context, params MessageNewParams, opts ...option.RequestOption) (res *Message, err error) {
	if !param.IsOmitted(params.UserProfileID) {
		opts = append(opts, option.WithHeader("anthropic-user-profile-id", fmt.Sprintf("%v", params.UserProfileID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/messages"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, params, &res, opts...)
	return res, err
}

type Message struct {
	// Unique object identifier.
	//
	// The format and length of IDs may change over time.
	ID string `json:"id" api:"required"`
	// Content generated by the model.
	//
	// Example:
	//
	// ```json
	// [{ "type": "text", "text": "Hi, I'm Claude." }]
	// ```
	Content []ContentBlockUnion `json:"content" api:"required"`
	// The model that will complete your prompt.
	Model Model `json:"model" api:"required"`
	// Conversational role of the generated message.
	//
	// This will always be `"assistant"`.
	Role constant.Assistant `json:"role" default:"assistant"`
	// The reason that we stopped.
	StopReason StopReason `json:"stop_reason" api:"required"`
	// Object type.
	//
	// For Messages, this is always `"message"`.
	Type constant.Message `json:"type" default:"message"`
	// Billing and rate-limit usage.
	Usage Usage `json:"usage" api:"required"`
	// JSON contains metadata for fields, check [respjson.Field] for more details.
	JSON struct {
		ID          respjson.Field
		Content     respjson.Field
		Model       respjson.Field
		Role        respjson.Field
		StopReason  respjson.Field
		Type        respjson.Field
		Usage       respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}
