/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the service is up. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The bundles published for this API, newest first. */
        get: operations["listBundles"];
        put?: never;
        /**
         * Publish a signed evolution bundle.
         * @description The bundle is verified here, against a publisher key registered for
         *     this API before the request was made, not trusted because it arrived.
         *     Publishing the same bundle again is not an error and changes nothing.
         */
        post: operations["publishBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bundles/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One bundle, as the signed envelope it was published as. */
        get: operations["getBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report what running adapters did, as hourly counters.
         * @description Counts are added to what is already recorded for the same hour, so a
         *     batch retried with the same `Idempotency-Key` is counted once and a
         *     batch sent twice without one is counted twice. Rows this API cannot
         *     read are skipped and counted in `ignored`, never the whole batch: a
         *     runtime must not lose an hour of counters over one bad row.
         */
        post: operations["ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Say that a runtime is running, and with what.
         * @description Sent on start and then periodically. It is what tells "no caller used
         *     this contract" apart from "the usage sink was never wired up", which
         *     counters alone cannot, and what shows a fleet running two programs at
         *     once during a deploy.
         */
        post: operations["heartbeat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The flags a runtime should apply now.
         * @description Polled by every running runtime, so the usual answer is `304`. A
         *     runtime that cannot reach this keeps the last flags it read, on disk
         *     across restarts, which is why this being down is not an incident.
         */
        get: operations["getFlags"];
        /**
         * Change the flags, saying why.
         * @description The flags a person changes are the ones they last read: a change made
         *     from a stale view is refused with `412` rather than silently undoing
         *     somebody else's kill switch. Every change is kept, with who made it
         *     and why.
         */
        put: operations["setFlags"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flags/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every change to the flags, newest first. */
        get: operations["listFlagChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every contract this API has released, and whether it is still used. */
        get: operations["listContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{label}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One contract, and the Changes still applied for its callers. */
        get: operations["getContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How much traffic each Change still carries, and whether a contract can retire.
         * @description What the release gate reads before blocking a breaking change that
         *     active consumers cannot be migrated past, and what a provider reads
         *     before retiring a contract.
         */
        get: operations["getImpact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draft Changes between two versions of a contract.
         * @description The same drafting the CLI does offline with rules alone, with the
         *     model judges added, whose keys live only in this service. The CLI
         *     falls back to rules when this cannot be reached. Documents are read
         *     with external references refused, so nothing here fetches a URL a
         *     document names.
         */
        post: operations["propose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consumers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The callers seen on old contracts, most recently seen first.
         * @description A consumer is known only by the hashed key the runtime reported, and
         *     by the repositories linked to it, if its owner linked any.
         */
        get: operations["listConsumers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A single-use link a consumer follows to connect their repositories.
         * @description Sent by the provider to a consumer who is still on an old contract.
         *     Following it installs the GitHub App on the repositories the consumer
         *     chooses and binds them to this API and that consumer, after which
         *     migration pull requests arrive without anyone asking for them.
         */
        post: operations["createLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The consumer repositories connected to this API. */
        get: operations["listIntegrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Migration pull requests opened in consumer repositories, newest first. */
        get: operations["listMigrations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sdks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The SDK maps this API has, by package. */
        get: operations["listSdks"];
        /**
         * Say how an SDK names what the contract describes.
         * @description One map per package, replaced whole each time it is sent: which type
         *     the SDK exports for each schema, which accessor calls each operation,
         *     and the package that speaks the current contract. The migration
         *     service reads it to find where a consumer's code touches what a
         *     release changed. A consumer whose SDK has no map is told what changed
         *     and gets no pull request.
         */
        put: operations["putSdk"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tokens issued for this API. A token's secret is never shown again. */
        get: operations["listTokens"];
        put?: never;
        /**
         * Issue a token with the scopes a job needs and no more.
         * @description A runtime needs `ingest` and `flags:read`; CI needs `publish` and
         *     `read`. A token that can write flags should not be sitting in every
         *     container.
         */
        post: operations["createToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a token. It stops working at once and cannot be restored. */
        delete: operations["revokeToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The keys bundles for this API may be signed with. */
        get: operations["listKeys"];
        put?: never;
        /** Register a public key bundles may be signed with. */
        post: operations["addKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/keys/{keyid}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a publisher key, and quarantine every bundle it signed.
         * @description A key that leaked may have signed bundles nobody meant to publish, so
         *     revoking it withdraws everything it signed from distribution. A bundle
         *     that should stay published is signed again with a key still trusted.
         */
        post: operations["revokeKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/v1/apis/{api}/bundles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An API's published bundles, for anyone.
         * @description What a consumer with no account reads to migrate locally. Served from
         *     a cache. Trust never rests on this service: a reader verifies each
         *     bundle against the publisher key the provider serves from its own
         *     domain, at `/.well-known/invariant.json`.
         */
        get: operations["listPublicBundles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/v1/apis/{api}/bundles/{digest}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One published bundle, for anyone. */
        get: operations["getPublicBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description What went wrong and what to do about it, for a person. */
                message: string;
                /** @description Quote this when asking for help. */
                requestId?: string;
            };
        };
        /**
         * @description Stable once published, so a client can branch on it.
         * @enum {string}
         */
        ErrorCode: "malformed" | "unauthenticated" | "insufficient_scope" | "wrong_api" | "not_found" | "no_publisher_key" | "rejected" | "idempotency_conflict" | "already_exists" | "too_large" | "unreadable_contract" | "stale" | "precondition_required" | "rate_limited" | "internal";
        ApiId: string;
        /** @description A contract's label, as the provider named it, such as `2026-01-15`. */
        ContractLabel: string;
        Digest: string;
        /** @description The SHA-256 of the key's SPKI encoding. */
        KeyId: string;
        /** @description A Change's id, as its file names it. */
        ChangeId: string;
        /**
         * @description A consumer's key as the runtime hashed it, so the key itself never
         *     leaves the provider.
         */
        ConsumerKey: string;
        /** @description Seconds since the Unix epoch. */
        Timestamp: number;
        /** @description The start of an hour, in seconds since the Unix epoch. */
        Hour: number;
        /** @enum {string} */
        Scope: "read" | "publish" | "ingest" | "flags:read" | "flags:write" | "propose" | "admin";
        /** @description A DSSE envelope carrying an in-toto statement about one release. */
        DsseEnvelope: {
            /** @constant */
            payloadType: "application/vnd.in-toto+json";
            /** @description The statement, base64 encoded. */
            payload: string;
            signatures: {
                keyid: string;
                sig: string;
            }[];
        };
        BundlePublished: {
            digest: components["schemas"]["Digest"];
            created: boolean;
            api: components["schemas"]["ApiId"];
            to: components["schemas"]["ContractLabel"];
        };
        BundleSummary: {
            digest: components["schemas"]["Digest"];
            from: components["schemas"]["ContractLabel"];
            to: components["schemas"]["ContractLabel"];
            keyid: components["schemas"]["KeyId"];
            publishedAt: components["schemas"]["Timestamp"];
        };
        BundlePage: {
            bundles: components["schemas"]["BundleSummary"][];
            /** @description Pass as `cursor` for the next page. Absent on the last. */
            next?: string;
        };
        /** @description At most 5,000 rows in all. */
        IngestBatch: {
            usage?: components["schemas"]["UsageRow"][];
            outcomes?: components["schemas"]["OutcomeRow"][];
        };
        /** @description How many times one Change was applied for one consumer in one hour. */
        UsageRow: {
            /** @description Absent when the runtime could not tell who called. */
            consumer?: components["schemas"]["ConsumerKey"];
            contract: components["schemas"]["ContractLabel"];
            changeId: components["schemas"]["ChangeId"];
            hour: components["schemas"]["Hour"];
            count: number;
        };
        /**
         * @description How adapted requests, responses and payloads ended, in one hour. Never
         *     a body or a field value: `reason` is the runtime's own message.
         */
        OutcomeRow: {
            contract: components["schemas"]["ContractLabel"];
            operation: string;
            /** @enum {string} */
            direction: "request" | "response" | "outbound";
            /** @enum {string} */
            outcome: "adapted" | "refused" | "failed";
            reason?: string;
            hour: components["schemas"]["Hour"];
            count: number;
        };
        IngestResult: {
            accepted: number;
            /** @description Rows skipped because they could not be read. */
            ignored: number;
        };
        Heartbeat: {
            /** @description Stable for the life of one process, and nothing that identifies a host. */
            instance: string;
            runtime: {
                version: string;
                /** @description How the runtime is attached, such as `hono`, `express` or `proxy`. */
                binding: string;
            };
            program: {
                digest: components["schemas"]["Digest"];
                compiledBy?: string;
                minRuntime?: string;
                currentLabel?: components["schemas"]["ContractLabel"];
            };
            flags?: {
                /** @description The flags in force, or absent when none were ever read. */
                etag?: string;
                /** @enum {string} */
                source?: "remote" | "disk" | "file" | "none";
            };
            startedAt: components["schemas"]["Timestamp"];
        };
        Flags: {
            /** @description Stops all compatibility work. Old contracts are refused rather than mis-served. */
            allDisabled?: boolean;
            disabledContracts?: components["schemas"]["ContractLabel"][];
            disabledChanges?: components["schemas"]["ChangeId"][];
        };
        FlagsState: {
            flags: components["schemas"]["Flags"];
            updatedAt: components["schemas"]["Timestamp"];
            /** @description The token or person that made the last change. */
            updatedBy?: string;
        };
        FlagsChange: {
            flags: components["schemas"]["Flags"];
            /** @description Why, for whoever reads the history during the incident. */
            reason: string;
        };
        FlagChange: {
            flags: components["schemas"]["Flags"];
            reason: string;
            actor: string;
            at: components["schemas"]["Timestamp"];
        };
        FlagChangePage: {
            changes: components["schemas"]["FlagChange"][];
            next?: string;
        };
        /**
         * @description `current` is what the provider's handlers speak. `served` is an old
         *     contract adapted for its callers. `retiring` has a date after which it
         *     is refused. `retired` is refused with guidance now.
         * @enum {string}
         */
        ContractStatus: "current" | "served" | "retiring" | "retired";
        Contract: {
            label: components["schemas"]["ContractLabel"];
            status: components["schemas"]["ContractStatus"];
            releasedAt: components["schemas"]["Timestamp"];
            retireAfter?: components["schemas"]["Timestamp"];
            /** @description Distinct consumers seen on it in the last 30 days. */
            consumers?: number;
            lastSeen?: components["schemas"]["Timestamp"];
        };
        ContractDetail: components["schemas"]["Contract"] & {
            bundle?: components["schemas"]["Digest"];
            /** @description The Changes a caller on this contract is served through. */
            changes: {
                id: components["schemas"]["ChangeId"];
                summary: string;
                /** @description Times applied in the last 30 days. */
                applied?: number;
            }[];
        };
        Impact: {
            days: number;
            contracts: {
                label: components["schemas"]["ContractLabel"];
                consumers: number;
                requests: number;
                changes: {
                    id: components["schemas"]["ChangeId"];
                    applied: number;
                    consumers: number;
                }[];
                /**
                 * @description No consumer used it in the window and a runtime reported
                 *     throughout it, so the silence is not a missing sink.
                 */
                retirable: boolean;
            }[];
        };
        /** @description At most 20 MB in all. */
        ProposeRequest: {
            /** @description The released contract, as an OpenAPI 3 or Swagger 2.0 document. */
            from: {
                [key: string]: unknown;
            };
            /** @description The contract being released. */
            to: {
                [key: string]: unknown;
            };
            /** @description Anything the provider wants the judges to know, such as a changelog entry. */
            context?: string;
        };
        Proposal: {
            drafts: {
                /** @description A Change, in the IR's own format. */
                change: {
                    [key: string]: unknown;
                };
                /** @enum {string} */
                judge: "rules" | "jev" | "s2";
                confidence: number;
                /** @enum {string} */
                attention: "normal" | "review";
                notes?: string[];
            }[];
            decisions: {
                /** @enum {string} */
                kind: "vocabulary" | "value";
                schema: string;
                field: string;
                why: string;
            }[];
            unresolved: {
                schema: string;
                field: string;
                reason: string;
            }[];
        };
        Consumer: {
            consumer: components["schemas"]["ConsumerKey"];
            contracts: {
                label: components["schemas"]["ContractLabel"];
                lastSeen: components["schemas"]["Timestamp"];
                requests: number;
            }[];
            lastSeen: components["schemas"]["Timestamp"];
            /** @description The ids of the integrations linked to this consumer. */
            integrations?: string[];
        };
        ConsumerPage: {
            consumers: components["schemas"]["Consumer"][];
            next?: string;
        };
        Integration: {
            id: string;
            consumer: components["schemas"]["ConsumerKey"];
            /** @enum {string} */
            provider: "github";
            repositories: string[];
            connectedAt: components["schemas"]["Timestamp"];
        };
        IntegrationPage: {
            integrations: components["schemas"]["Integration"][];
            next?: string;
        };
        /** @enum {string} */
        MigrationStatus: "queued" | "running" | "opened" | "merged" | "closed" | "failed";
        Migration: {
            id: string;
            integration: string;
            repository: string;
            bundle: components["schemas"]["Digest"];
            status: components["schemas"]["MigrationStatus"];
            /** Format: uri */
            pullRequest?: string;
            /** @description Why it failed or was closed, when it was. */
            reason?: string;
            updatedAt: components["schemas"]["Timestamp"];
        };
        MigrationPage: {
            migrations: components["schemas"]["Migration"][];
            next?: string;
        };
        /** @description How one SDK package names what the contract describes. */
        SdkMap: {
            /** @description The package consumers depend on today, as their manifest names it. */
            package: string;
            /** @description The package that speaks the current contract, and what it calls each schema where that differs. */
            upgradeTo: {
                package: string;
                version: string;
                types?: {
                    [key: string]: string;
                };
            };
            /** @description Schema name in the contract to the type the SDK exports for it. */
            types: {
                [key: string]: string;
            };
            /** @description Where a consumer names the contract it speaks, as an `apiVersion` option. */
            pin?: {
                type: string;
                property: string;
                label: string;
            };
            /** @description The SDK method that calls each operation, keyed `method path`. */
            operations?: {
                [key: string]: {
                    type: string;
                    method: string;
                };
            };
            /** @description Resource accessor paths that moved, `charges.create` to `payments.create`. */
            accessors: {
                from: string[];
                to: string[];
            }[];
            /** @description Exact conversion helpers, so no float arithmetic is written into a consumer's code. */
            helpers?: {
                toMinor: string;
                fromMinor: string;
                from?: string;
                emit?: {
                    path: string;
                };
            };
        };
        Token: {
            id: string;
            name: string;
            /** @description The first characters of the secret, so a leaked token can be recognised. */
            prefix: string;
            scopes: components["schemas"]["Scope"][];
            createdAt: components["schemas"]["Timestamp"];
            expiresAt?: components["schemas"]["Timestamp"];
            lastUsedAt?: components["schemas"]["Timestamp"];
            revokedAt?: components["schemas"]["Timestamp"];
        };
        IssuedToken: components["schemas"]["Token"] & {
            /** @description The token. Shown only in this response. */
            secret: string;
        };
        PublisherKey: {
            keyid: components["schemas"]["KeyId"];
            name: string;
            publicKey: string;
            addedAt: components["schemas"]["Timestamp"];
            notAfter?: components["schemas"]["Timestamp"];
            revokedAt?: components["schemas"]["Timestamp"];
            revokedReason?: string;
        };
    };
    responses: {
        /** @description The request could not be read as this contract describes it. */
        Malformed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No token, or a token this service did not issue, has revoked, or has seen expire. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The token lacks the scope this operation needs, or is for another API. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Nothing by that name for this API. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The request contradicts what is already recorded. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The body is larger than this operation accepts. */
        TooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A document in the request is not a contract this service can read. */
        Unreadable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description What is being changed has changed since the client read it. */
        Stale: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description This change must name the version it was made from, in `If-Match`. */
        PreconditionRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. Wait as long as `Retry-After` says. */
        RateLimited: {
            headers: {
                /** @description Seconds to wait. */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description The contract of this API the client was written against. */
        InvariantVersion: components["schemas"]["ContractLabel"];
        /**
         * @description Makes a retried write take effect once. A key reused within a day with
         *     a different body is refused with `409`.
         */
        IdempotencyKey: string;
        /** @description The `next` of the previous page. */
        Cursor: string;
        Limit: number;
        Digest: components["schemas"]["Digest"];
        Label: components["schemas"]["ContractLabel"];
        KeyId: components["schemas"]["KeyId"];
        Api: components["schemas"]["ApiId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
        };
    };
    listBundles: {
        parameters: {
            query?: {
                /** @description The `next` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of bundles. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundlePage"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    publishBundle: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /**
                 * @description Makes a retried write take effect once. A key reused within a day with
                 *     a different body is refused with `409`.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DsseEnvelope"];
            };
        };
        responses: {
            /** @description Already published; nothing changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundlePublished"];
                };
            };
            /** @description Published. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundlePublished"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    getBundle: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path: {
                digest: components["parameters"]["Digest"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The envelope, to be verified by the reader against the publisher's key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DsseEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    ingest: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /**
                 * @description Makes a retried write take effect once. A key reused within a day with
                 *     a different body is refused with `409`.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestBatch"];
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    heartbeat: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Heartbeat"];
            };
        };
        responses: {
            /** @description Recorded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getFlags: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /** @description The `ETag` of the flags the runtime already holds. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current flags. */
            200: {
                headers: {
                    /** @description Sent back as `If-None-Match` on the next poll, and as `If-Match` to change them. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagsState"];
                };
            };
            /** @description Unchanged since the flags named in `If-None-Match`. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    setFlags: {
        parameters: {
            query?: never;
            header: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /** @description The `ETag` of the flags this change was made from. */
                "If-Match": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlagsChange"];
            };
        };
        responses: {
            /** @description Changed. */
            200: {
                headers: {
                    /** @description The new flags' tag. */
                    ETag: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagsState"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            412: components["responses"]["Stale"];
            428: components["responses"]["PreconditionRequired"];
            429: components["responses"]["RateLimited"];
        };
    };
    listFlagChanges: {
        parameters: {
            query?: {
                /** @description The `next` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of changes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlagChangePage"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listContracts: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contracts, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contracts: components["schemas"]["Contract"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getContract: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path: {
                label: components["parameters"]["Label"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDetail"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getImpact: {
        parameters: {
            query?: {
                /** @description How far back to count, in days. */
                days?: number;
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage per contract and Change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Impact"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    propose: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description The drafts, the decisions only the provider can make, and what nothing expresses. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
            422: components["responses"]["Unreadable"];
            429: components["responses"]["RateLimited"];
        };
    };
    listConsumers: {
        parameters: {
            query?: {
                /** @description Only consumers seen on this contract. */
                contract?: components["schemas"]["ContractLabel"];
                /** @description The `next` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of consumers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsumerPage"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    createLink: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /**
                 * @description Makes a retried write take effect once. A key reused within a day with
                 *     a different body is refused with `409`.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    consumer: components["schemas"]["ConsumerKey"];
                    /** @default 14 */
                    expiresInDays?: number;
                };
            };
        };
        responses: {
            /** @description The link, shown once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        url: string;
                        expiresAt: components["schemas"]["Timestamp"];
                    };
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: {
                /** @description The `next` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of integrations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationPage"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listMigrations: {
        parameters: {
            query?: {
                status?: components["schemas"]["MigrationStatus"];
                /** @description The `next` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of migrations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationPage"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    listSdks: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every map. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sdks: components["schemas"]["SdkMap"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    putSdk: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SdkMap"];
            };
        };
        responses: {
            /** @description Stored, replacing any map this package had. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SdkMap"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            413: components["responses"]["TooLarge"];
            429: components["responses"]["RateLimited"];
        };
    };
    listTokens: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every token, revoked ones included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tokens: components["schemas"]["Token"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    createToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /**
                 * @description Makes a retried write take effect once. A key reused within a day with
                 *     a different body is refused with `409`.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    scopes: components["schemas"]["Scope"][];
                    expiresAt?: components["schemas"]["Timestamp"];
                };
            };
        };
        responses: {
            /** @description The token, whose secret is shown this once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssuedToken"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    revokeToken: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked, or already revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every key, revoked ones included. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys: components["schemas"]["PublisherKey"][];
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    addKey: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
                /**
                 * @description Makes a retried write take effect once. A key reused within a day with
                 *     a different body is refused with `409`.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @description An Ed25519 or ECDSA P-256 public key, PEM encoded (SPKI). */
                    publicKey: string;
                    notAfter?: components["schemas"]["Timestamp"];
                };
            };
        };
        responses: {
            /** @description Registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublisherKey"];
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path: {
                keyid: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key: components["schemas"]["PublisherKey"];
                        /** @description Bundles signed with this key, now withdrawn. */
                        quarantined: number;
                    };
                };
            };
            400: components["responses"]["Malformed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listPublicBundles: {
        parameters: {
            query?: {
                /** @description The `next` of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path: {
                api: components["parameters"]["Api"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of bundles. */
            200: {
                headers: {
                    "Cache-Control": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundlePage"];
                };
            };
            400: components["responses"]["Malformed"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getPublicBundle: {
        parameters: {
            query?: never;
            header?: {
                /** @description The contract of this API the client was written against. */
                "Invariant-Version"?: components["parameters"]["InvariantVersion"];
            };
            path: {
                api: components["parameters"]["Api"];
                digest: components["parameters"]["Digest"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The envelope. Immutable, so cached indefinitely. */
            200: {
                headers: {
                    "Cache-Control": string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DsseEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
}
