"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7518c67b81ea

from .sdkconfiguration import SDKConfiguration
import httpx
from mistralai.client import errors, models, utils


class BaseSDK:
    sdk_configuration: SDKConfiguration
    parent_ref: Optional[object] = None
    """
    Reference to the root SDK instance, if any. This will prevent it from
    being garbage collected while there are active streams.
    """

    def __init__(
        self,
        sdk_config: SDKConfiguration,
        parent_ref: Optional[object] = None,
    ) -> None:
        self.sdk_configuration = sdk_config
        self.parent_ref = parent_ref
