# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from ..model import Model
from ..._models import BaseModel

__all__ = ["BetaMessage"]


class BetaMessage(BaseModel):
    id: str
    """Unique object identifier.

    The format and length of IDs may change over time.
    """

    content: List[object]
    """Content generated by the model.

    Example:

    ```json
    [{ "type": "text", "text": "Hi, I'm Claude." }]
    ```
    """

    model: Model

    role: Literal["assistant"]

    type: Literal["message"]
