# coding: utf-8

"""
    Ory APIs

    The version of the OpenAPI document: v1.22.28
    Contact: support@ory.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JsonPatch(BaseModel):
    """
    A JSONPatch document as defined by RFC 6902
    """ # noqa: E501
    var_from: Optional[StrictStr] = Field(default=None, description="This field is used together with operation \"move\" and uses JSON Pointer notation.  Learn more [about JSON Pointers](https://datatracker.ietf.org/doc/html/rfc6901#section-5).", alias="from")
    op: StrictStr = Field(description="The operation to be performed. One of \"add\", \"remove\", \"replace\", \"move\", \"copy\", or \"test\".")
    path: StrictStr = Field(description="The path to the target path. Uses JSON pointer notation.  Learn more [about JSON Pointers](https://datatracker.ietf.org/doc/html/rfc6901#section-5).")
    value: Optional[Any] = Field(default=None, description="The value to be used within the operations.  Learn more [about JSON Pointers](https://datatracker.ietf.org/doc/html/rfc6901#section-5).")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["from", "op", "path", "value"]

    @field_validator('op')
    def op_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['add', 'remove', 'replace', 'move', 'copy', 'test']):
            raise ValueError("must be one of enum values ('add', 'remove', 'replace', 'move', 'copy', 'test')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )
