# coding: utf-8

"""
    Ory APIs

    The version of the OpenAPI document: v1.22.28
    Contact: support@ory.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class UiNodeAnchorAttributes(BaseModel):
    """
    UiNodeAnchorAttributes
    """ # noqa: E501
    href: StrictStr = Field(description="The link's href (destination) URL.  format: uri")
    id: StrictStr = Field(description="A unique identifier")
    node_type: StrictStr = Field(description="NodeType represents this node's types. It is a mirror of `node.type` and is primarily used to allow compatibility with OpenAPI 3.0.  In this struct it technically always is \"a\". text Text input Input img Image a Anchor script Script div Division")
    title: UiText
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["href", "id", "node_type", "title"]

    @field_validator('node_type')
    def node_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['a']):
            raise ValueError("must be one of enum values ('a')")
        return value
