# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .assistant_message import AssistantMessage
    from .embed_by_type_response_embeddings import EmbedByTypeResponseEmbeddings
_dynamic_imports: typing.Dict[str, str] = {
    "AssistantMessage": ".assistant_message",
    "EmbedByTypeResponseEmbeddings": ".embed_by_type_response_embeddings",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    module = import_module(module_name, __package__)
    if module_name == f".{attr_name}":
        return module
    else:
        return getattr(module, attr_name)


__all__ = [
    "AssistantMessage",
    "EmbedByTypeResponseEmbeddings",
]
