/**
 * Writes docs/reference/breaking-changes.md: every check the pinned oasdiff
 * binary knows, as the catalogue classifies it, which is what the gate and
 * the pull request comment say about each. Generated, never edited; the docs
 * test fails when it is stale.
 *
 *   node --import tsx scripts/docs-catalogue.mts [--check]
 */
import { execFile } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { promisify } from "node:util";
import {
  type CatalogueClass,
  catalogueEntry,
  OASDIFF_VERSION,
  oasdiffBinary,
} from "@invariant/diff";

const OUT = join(import.meta.dirname, "../docs/reference/breaking-changes.md");

const CLASSES: { class: CatalogueClass; title: string; about: string }[] = [
  {
    class: "adaptable",
    title: "Served automatically",
    about:
      "A Change the rules draft with nobody deciding anything, and the runtime serves.",
  },
  {
    class: "needs-decision",
    title: "Served once you decide",
    about:
      "A Change the runtime serves once you answer a question, such as what an old caller is sent in place of a value it never knew.",
  },
  {
    class: "behavior-only",
    title: "Behavior only",
    about:
      "No translation can hide it. A `behavior` flag lets your own code serve old callers as before.",
  },
  {
    class: "process",
    title: "Process",
    about: "Rules about how an API is deprecated, which no caller sees.",
  },
];

export async function render(): Promise<string> {
  const { stdout } = await promisify(execFile)(
    oasdiffBinary(),
    ["checks", "changelog", "--format", "json"],
    {
      maxBuffer: 16 * 1024 * 1024,
    },
  );
  const checks = (
    JSON.parse(stdout) as { id: string; level: "error" | "warning" | "info" }[]
  )
    .map((check) => ({ ...check, entry: catalogueEntry(check.id, check.level) }))
    .filter((check) => check.entry.class !== "non-breaking")
    .sort((a, b) => a.id.localeCompare(b.id));
  const cell = (text: string) => text.replaceAll("|", "\\|").replaceAll("\n", " ");
  const sections = CLASSES.map((group) => {
    const rows = checks.filter((check) => check.entry.class === group.class);
    return `## ${group.title}\n\n${group.about} ${rows.length} checks.\n\n| Check | Op | Served | What it means |\n|---|---|---|---|\n${rows
      .map(
        (check) =>
          `| \`${check.id}\` | ${check.entry.op ? `\`${check.entry.op}\`` : ""} | ${check.entry.served} | ${cell(check.entry.sentence)} |`,
      )
      .join("\n")}\n`;
  });
  return `# Breaking changes\n\n<!-- Generated by scripts/docs-catalogue.mts from oasdiff ${OASDIFF_VERSION}. Do not edit. -->\n\nEvery breaking change the pinned differ (oasdiff ${OASDIFF_VERSION}) can report, and what Invariant does about it: the same words the release gate and the pull request comment use. ${checks.length} checks in all.\n\n${sections.join("\n")}`;
}

if (process.argv[1]?.endsWith("docs-catalogue.mts")) {
  const text = await render();
  if (process.argv.includes("--check")) {
    if ((await readFile(OUT, "utf8").catch(() => "")) !== text) {
      process.stderr.write(
        "docs/reference/breaking-changes.md is stale; run scripts/docs-catalogue.mts\n",
      );
      process.exit(1);
    }
  } else {
    await writeFile(OUT, text);
    process.stdout.write(`wrote ${OUT}\n`);
  }
}
