/**
 * Writes each package's version into the source that has to know it.
 *
 * A compiled program records what compiled it and the oldest runtime that can
 * run it, and the runtime compares that against its own version. Both come from
 * `package.json`, which Changesets bumps, and a bundler inlining a JSON import
 * would put the whole manifest into every provider's request path. So the
 * version is copied into a constant here, run straight after
 * `changeset version`, and `version.test.ts` fails if the two ever differ.
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");

for (const name of ["ir", "runtime"]) {
  const manifest = JSON.parse(
    await readFile(join(ROOT, "packages", name, "package.json"), "utf8"),
  ) as { version: string };
  await writeFile(
    join(ROOT, "packages", name, "src", "version.ts"),
    [
      "// Generated by scripts/sync-versions.mts from package.json. Do not edit.",
      `export const VERSION = ${JSON.stringify(manifest.version)};`,
      "",
    ].join("\n"),
  );
}

// The Go engine runs the same programs as the runtime and refuses the same
// ones, so it states the runtime's version.
const runtime = JSON.parse(
  await readFile(join(ROOT, "packages", "runtime", "package.json"), "utf8"),
) as { version: string };
await writeFile(
  join(ROOT, "engines", "go", "invariant", "version.go"),
  [
    "// Code generated by scripts/sync-versions.mts from packages/runtime/package.json. DO NOT EDIT.",
    "",
    "package invariant",
    "",
    "// Version is the runtime version this engine implements, which a program's",
    "// minRuntime is compared against.",
    `const Version = ${JSON.stringify(runtime.version)}`,
    "",
  ].join("\n"),
);
