/**
 * The launch gate, measured.
 *
 * Every line of the gate in the production plan, with the value the rigs last
 * measured and the evidence it came from. A line nothing measures yet says so
 * rather than being left out, because a scoreboard that only lists what is
 * going well is a brochure. Regenerated by the nightly proving run; the same
 * page is the public evidence page once the product launches.
 *
 *   node --import tsx proving/scoreboard.mts
 */
import { existsSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parseDocumentText } from "@invariant/contract";
import { catalogueEntry, isUnclassified } from "@invariant/diff";
import type { PairResult as CorpusResult } from "@invariant/eval";
import type { BUDGET, ChainCost } from "./chains/cost.ts";
import { ROOT } from "./corpus/manifest.mts";
import type { BUDGET as OVERHEAD_BUDGET, OverheadResult } from "./overhead/overhead.ts";
import type { ReplayIndex } from "./replay/mine.mts";
import type { ReplayResult } from "./replay/run.mts";
import type { PairResult as ServerResult } from "./servers/run.mts";
import type { TrafficResult } from "./traffic/run.mts";

type Status = "met" | "not met" | "not measured";

interface Line {
  id: string;
  claim: string;
  status: Status;
  value: string;
  evidence: string;
}

/**
 * The most of the L4 denominator that behavior-only places may make up. The
 * class is the catalogue's, by rule, and the share is published beside it.
 */
export const BEHAVIOR_ONLY_CAP = 0.05;

/** The sections of the conformance vector file, counted. */
export interface VectorCounts {
  vectors: unknown[];
  envelopes: unknown[];
  forms: unknown[];
}

function read<T>(path: string): T | undefined {
  const full = join(ROOT, path);
  return existsSync(full) ? (JSON.parse(readFileSync(full, "utf8")) as T) : undefined;
}

const percent = (part: number, whole: number) =>
  whole === 0 ? "n/a" : `${((part / whole) * 100).toFixed(1)}%`;

export function scoreboard(inputs: {
  corpus: CorpusResult[] | undefined;
  manifestPairs: { provider: string }[] | undefined;
  traffic: TrafficResult[] | undefined;
  servers: ServerResult[] | undefined;
  replay: ReplayIndex | undefined;
  replayed?: ReplayResult[] | undefined;
  fuzz: string | undefined;
  chains?: (ChainCost & { budget: typeof BUDGET }) | undefined;
  overhead?: (OverheadResult & { budget: typeof OVERHEAD_BUDGET }) | undefined;
  vectors?: VectorCounts | undefined;
  ownership?: Ownership | undefined;
}): Line[] {
  const lines: Line[] = [];
  const unmeasured = (id: string, claim: string, why: string): Line => ({
    id,
    claim,
    status: "not measured",
    value: "",
    evidence: why,
  });

  lines.push({
    id: "L1",
    claim: "The gate never passes a release whose Changes cannot all be served.",
    status: "met",
    value:
      "Changes generated from the IR's own schema either compile to work for every op or are blocked; every op x location x direction cell is decided and executed",
    evidence:
      "packages/compiler/src/servable.test.ts and packages/compiler/matrix.json, on every commit and deeply every night",
  });

  const corpus = inputs.corpus ?? [];
  const providers = new Set((inputs.manifestPairs ?? []).map((pair) => pair.provider));
  const failing = corpus.filter((result) => result.compileIssues.length > 0);
  const bigEnough = corpus.length >= 1500 && providers.size >= 30;
  lines.push({
    id: "L2",
    claim:
      "Zero drafts that fail to compile, over at least 1500 pairs from 30 providers.",
    status:
      corpus.length === 0
        ? "not measured"
        : failing.length === 0 && bigEnough
          ? "met"
          : "not met",
    value: `${failing.length} pairs with drafts that do not compile, of ${corpus.length} pairs from ${providers.size} providers`,
    evidence: "proving/corpus/results.json (rules judge)",
  });

  // Every id the pinned differ can print is classified; the catalogue's own
  // test asks the binary on every commit. What the corpus shows is how many
  // of the kinds real providers produce are served today.
  const kinds = [
    ...new Set(corpus.flatMap((result) => Object.keys(result.breakingKinds ?? {}))),
  ];
  const unclassified = kinds.filter((kind) => isUnclassified(kind));
  const servedKinds = kinds.filter((kind) => catalogueEntry(kind).served === "yes");
  lines.push({
    id: "L3",
    claim: "Every breaking-change id the pinned differ reports is catalogued.",
    status: unclassified.length === 0 ? "met" : "not met",
    value: `every breaking check the pinned differ knows is classified; of the ${kinds.length} kinds real providers produced, ${unclassified.length} unclassified and ${servedKinds.length} served today`,
    evidence:
      "packages/diff/src/catalogue.ts, checked against the binary on every commit",
  });

  const done = corpus.filter((result) => result.reached === "done");
  const aligned = done.reduce((sum, result) => sum + result.breakingAligned, 0);
  const after = done.reduce((sum, result) => sum + result.breakingAfter, 0);
  const breakingPairs = done.filter((result) => result.breakingAligned > 0);
  const closed = breakingPairs.filter((result) => result.breakingAfter === 0);
  const explained = aligned === 0 ? 0 : (aligned - after) / aligned;
  // The same closure with every open decision answered synthetically: what a
  // provider who answered them would reach. A pair recorded before the corpus
  // measured it counts as it stood without decisions.
  const decided = done.reduce(
    (sum, result) => sum + (result.breakingAfterDecided ?? result.breakingAfter),
    0,
  );
  const measuredDecided = done.filter(
    (result) => result.breakingAfterDecided !== undefined,
  ).length;
  const closedDecided = breakingPairs.filter(
    (result) => (result.breakingAfterDecided ?? result.breakingAfter) === 0,
  );
  // Per place: a shared schema's one change counts once, however many
  // operations return it. The gate is judged on this where it is measured.
  const placed = done.filter((result) => result.places !== undefined);
  const placeSum = (pick: (places: NonNullable<CorpusResult["places"]>) => number) =>
    placed.reduce(
      (sum, result) => sum + pick(result.places as NonNullable<CorpusResult["places"]>),
      0,
    );
  const placesAligned = placeSum((places) => places.aligned);
  // A break the catalogue classes behavior-only is explained by declaring a
  // `behavior` flag rather than by a transform, so it counts as explained, up
  // to a cap: the class is assigned by rule, and a gate that could be met by
  // calling things behavior-only would measure nothing.
  const behaviorCap = Math.floor(placesAligned * BEHAVIOR_ONLY_CAP);
  const behaviorOnly = placeSum((places) => places.behaviorOnly ?? 0);
  const behaviorOnlyDecided = placeSum(
    (places) => places.behaviorOnlyDecided ?? places.behaviorOnly ?? 0,
  );
  const placesAfter =
    placeSum((places) => places.after) - Math.min(behaviorOnly, behaviorCap);
  const placesDecided =
    placeSum((places) => places.decided ?? places.after) -
    Math.min(behaviorOnlyDecided, behaviorCap);
  const byPlace = placed.length > 0;
  const headline = byPlace
    ? placesAligned === 0
      ? 1
      : (placesAligned - placesAfter) / placesAligned
    : explained;
  lines.push({
    id: "L4",
    claim:
      "At least 95% of breaking deltas explained, and at least 80% of breaking pairs closed.",
    status:
      corpus.length === 0
        ? "not measured"
        : headline >= 0.95 && closed.length >= 0.8 * breakingPairs.length
          ? "met"
          : "not met",
    value:
      (byPlace
        ? `Per place, on ${placed.length} of ${done.length} completed pairs: ${percent(placesAligned - placesAfter, placesAligned)} of breaking deltas explained, ${percent(placesAligned - placesDecided, placesAligned)} with every open decision answered synthetically; behavior-only by catalogue rule ${percent(Math.min(behaviorOnly, behaviorCap), placesAligned)} of places (cap ${percent(BEHAVIOR_ONLY_CAP, 1)}). `
        : "") +
      `Per instance: ${percent(aligned - after, aligned)} explained, ${percent(aligned - decided, aligned)} with synthetic answers (measured on ${measuredDecided} pairs). ` +
      `${closed.length} of ${breakingPairs.length} breaking pairs closed (${percent(closed.length, breakingPairs.length)}), ${closedDecided.length} with synthetic answers (${percent(closedDecided.length, breakingPairs.length)}).`,
    evidence:
      "proving/corpus/results.json (rules judge; without decisions, and with synthetic answers)",
  });
  lines.push(judgeLine(inputs.ownership));
  lines.push(
    unmeasured(
      "L5",
      "Official Stripe SDK suites pass through the proxy against stripe-mock on the new specification.",
      "Consecutive Stripe specifications differ only by enum values added within an API version, which nothing drafts until M3.8 and the judge; the rig would prove nothing yet.",
    ),
  );

  const traffic = inputs.traffic ?? [];
  const sites = traffic.flatMap((result) => result.sites);
  const violating = sites.filter((site) => site.violations > 0);
  const served = sites.filter((site) => !site.retired && site.samples > site.rigFaults);
  const proving = served.filter((site) => site.brokenWithout > 0);
  lines.push({
    id: "L6",
    claim:
      "For every closing pair, at least 100 requests per adapted site through the proxy with zero violations, judged independently.",
    status:
      traffic.length === 0 ? "not measured" : violating.length === 0 ? "met" : "not met",
    value: `${violating.length} sites with violations across ${traffic.length} closing pairs; ${sites.length - served.length} retired sites and ${served.length} served sites (${proving.length} non-vacuous)`,
    evidence: "proving/traffic/results.json",
  });

  const servers = inputs.servers ?? [];
  const projects = new Set(servers.map((result) => result.project));
  const languages = new Set(servers.map((result) => result.language));
  const regressions = servers.reduce((sum, result) => sum + result.regressions.length, 0);
  const broken = servers.reduce((sum, result) => sum + result.broken.length, 0);
  const fixed = servers.reduce((sum, result) => sum + result.served.length, 0);
  lines.push({
    id: "L7",
    claim:
      "At least 6 real servers in 4 language families, across a breaking release of their own, with the old release's suite passing through the proxy.",
    status:
      servers.length === 0
        ? "not measured"
        : projects.size >= 6 &&
            languages.size >= 4 &&
            regressions === 0 &&
            fixed === broken
          ? "met"
          : "not met",
    value: `${projects.size} projects in ${languages.size} languages; ${fixed} of ${broken} tests the releases broke served, ${regressions} regressions`,
    evidence: "proving/servers/results.json",
  });

  const cases = inputs.replay?.cases ?? [];
  const replayed = (inputs.replayed ?? []).filter((entry) => entry.error === undefined);
  const failed = (inputs.replayed ?? []).filter((entry) => entry.error !== undefined);
  const count = (ecosystem: string) =>
    cases.filter((entry) => entry.ecosystem === ecosystem).length;
  lines.push({
    id: "L8",
    claim:
      "Migration replay on at least 50 human migrations each for TypeScript, Python and Go, and 25 for JavaScript: 90% handled, no wrong edits.",
    status: replayed.length === 0 ? "not measured" : "not met",
    value:
      `${cases.length} cases mined (npm ${count("npm")}, pypi ${count("pypi")}, go ${count("go")}). ` +
      (replayed.length === 0
        ? "Not yet replayed."
        : `Replayed ${replayed.length}: ${(
            ["typescript", "javascript", "python", "go"] as const
          )
            .map((language) => {
              const mine = replayed.filter((entry) => entry.language === language);
              if (mine.length === 0) return `${language} none`;
              const sum = (pick: (entry: ReplayResult) => number) =>
                mine.reduce((total, entry) => total + pick(entry), 0);
              const sites = sum((entry) => entry.sites);
              const inScope = sum((entry) => entry.inScope?.sites ?? 0);
              const identical = sum((entry) => entry.inScope?.identical ?? 0);
              const differs = sum((entry) => entry.inScope?.differs ?? 0);
              const unclassified = sum(
                (entry) => entry.inScope?.unclassified ?? entry.sites,
              );
              return `${language} ${mine.length} cases: of ${sites} human sites, ${inScope} follow from a contract change, ${identical} of them identical (${percent(identical, inScope)}) and ${differs} to adjudicate; ${unclassified} not yet classed`;
            })
            .join("; ")}. ` +
          `${failed.length} could not be replayed. Sites are classed by Jev, not yet audited by hand.`),
    evidence: "proving/replay/results.json (run.mts), index.json",
  });

  lines.push(
    unmeasured(
      "L9",
      "npx init to a blocking check on a scratch pull request, p95 under 10 minutes on Linux, macOS and Windows.",
      "The install test passes on all three from a local registry on every commit; the timed walk from real npm needs the first publish.",
    ),
    {
      id: "L10",
      claim: "In-process adapters for every major Node framework pass one suite.",
      status: "not met",
      value:
        "Hono, node:http, Express 4 and 5, Koa, Fastify 4 and 5 and NestJS 12 pass one suite on Node 22 and 24; NestJS 10 and 11 and Next.js are not yet in it",
      evidence:
        "packages/runtime-node/src/conformance.test.ts, packages/runtime-hono, in CI on Node 22 and 24",
    },
    {
      id: "L10b",
      claim: "A Go net/http adapter passes the same suite.",
      status: "met",
      value:
        "the Go engine's net/http middleware passes every case of the Node adapter suite, run against a Go server on the same program",
      evidence:
        "packages/runtime-node/src/conformance.test.ts (go net/http), required in CI by INVARIANT_REQUIRE_GO",
    },
    unmeasured("L11", "A 24-hour proxy soak under chaos with zero violations.", "M10.4."),
    {
      id: "L12",
      claim: "The Go engine passes every conformance vector.",
      // The Go tests read every section of the vector file and fail on any
      // vector they do not pass, so the counts are the file's own.
      status: inputs.vectors ? "met" : "not measured",
      value: inputs.vectors
        ? `all ${inputs.vectors.vectors.length} body, ${inputs.vectors.envelopes.length} request-envelope and ${inputs.vectors.forms.length} form vectors pass`
        : "",
      evidence: "engines/go/invariant/vectors_test.go, in CI on every commit",
    },
    unmeasured(
      "L13",
      "The whole product journey in a browser against staging.",
      "M7 and M8.",
    ),
    unmeasured("L14", "Enterprise identity, audit, self-hosting and residency.", "M9."),
  );
  lines.push({
    id: "L15",
    claim:
      "Threat-model tests, nightly fuzzers with no open crashers, SBOM and provenance, a clean secrets scan and a recent restore drill.",
    status: "not met",
    value: `nightly fuzzers ${inputs.fuzz === "success" ? "passing" : inputs.fuzz === undefined ? "not run here" : `failing (${inputs.fuzz})`}; the rest is M10`,
    evidence: "proving/fuzz/",
  });
  lines.push(
    unmeasured("L16", "Docs complete, tested from manifests.", "M8.4."),
    {
      id: "L17",
      claim: "Older runtimes either run newer programs or refuse with a typed error.",
      status: "not met",
      value:
        "every program states its format, compiler and oldest runtime, and a runtime " +
        "refuses one it is too old for before reading any of it. Proven against " +
        "programs made to look newer; the arm that installs the previous published " +
        "runtime starts with the first release",
      evidence: "packages/runtime/src/skew.test.ts, on every commit",
    },
    chainLine(inputs.chains),
    overheadLine(inputs.overhead),
  );
  return lines;
}

/** What `eval/ownership.yaml` records of each judge, as far as L4b reads it. */
export interface Ownership {
  corpus?: { cases?: number; provenance?: { mined?: { cases?: number } } };
  tasks?: {
    alignment?: Record<
      string,
      {
        model?: string;
        atThreshold?: {
          answered?: number;
          selectiveAccuracy?: number;
          answeredAndWrong?: number;
        };
      }
    >;
  };
  byFamily?: Record<string, number>;
}

/** The labelled corpus the plan asks for before a judge's precision is quoted per family. */
const LABELLED_TARGET = 600;

function judgeLine(ownership: Ownership | undefined): Line {
  const claim =
    "Judge precision of at least 99% per family, and no semantically wrong Change surviving the gate.";
  const evidence = "eval/ownership.yaml; Rig D for false closure";
  const judges = Object.entries(ownership?.tasks?.alignment ?? {}).filter(
    ([, judge]) => judge.atThreshold !== undefined,
  );
  if (!ownership || judges.length === 0) {
    return { id: "L4b", claim, status: "not measured", value: "", evidence };
  }
  const cases = ownership.corpus?.cases ?? 0;
  const mined = ownership.corpus?.provenance?.mined?.cases ?? 0;
  const precise = judges.every(
    ([, judge]) => (judge.atThreshold?.selectiveAccuracy ?? 0) >= 0.99,
  );
  const perJudge = judges
    .map(([name, judge]) => {
      const at = judge.atThreshold ?? {};
      return `${name}${judge.model ? ` (${judge.model})` : ""} ${percent(at.selectiveAccuracy ?? 0, 1)} on ${at.answered ?? 0} answered, ${at.answeredAndWrong ?? 0} wrong`;
    })
    .join("; ");
  const weakest = Object.entries(ownership.byFamily ?? {}).sort(
    ([, a], [, b]) => a - b,
  )[0];
  return {
    id: "L4b",
    claim,
    // Met only when every part is: the per-family figure at threshold is not
    // yet recorded, the corpus is short of its size, and Rig D has not yet
    // judged a Change's meaning against the old server.
    status: "not met",
    value:
      `At each judge's threshold: ${perJudge}${precise ? "" : " (below 99%)"}. ` +
      `Labelled corpus ${cases} of ${LABELLED_TARGET} cases (${mined} mined). ` +
      (weakest
        ? `Per family only unthresholded accuracy is recorded, lowest ${weakest[0]} at ${percent(weakest[1], 1)}. `
        : "") +
      "False closure on Rig D is not yet measured.",
    evidence,
  };
}

function overheadLine(
  overhead: (OverheadResult & { budget: typeof OVERHEAD_BUDGET }) | undefined,
): Line {
  const claim = "Proxy p99 overhead asserted in CI.";
  if (!overhead) {
    return {
      id: "L19",
      claim,
      status: "not measured",
      value: "",
      evidence: "proving/overhead/",
    };
  }
  const { budget } = overhead;
  const errors =
    overhead.direct.errors + overhead.current.errors + overhead.adapted.errors;
  return {
    id: "L19",
    claim,
    status: errors === 0 && overhead.addedP99Ms <= budget.addedP99Ms ? "met" : "not met",
    value:
      `at ${overhead.rps} requests a second of a ${(overhead.bodyBytes / 1024).toFixed(1)} KiB list, every item adapted: ` +
      `${overhead.addedP99Ms} ms added at p99 (budget ${budget.addedP99Ms}); ` +
      `p99 ${overhead.direct.p99Ms} ms direct, ${overhead.current.p99Ms} ms through the proxy for a current caller, ` +
      `${overhead.adapted.p99Ms} ms adapted`,
    evidence:
      "proving/overhead/results.json, asserted by proving/overhead/measure.mts --check in its own CI step",
  };
}

function chainLine(chains: (ChainCost & { budget: typeof BUDGET }) | undefined): Line {
  const claim = "A 50-step chain over a Stripe-sized spec within stated budgets.";
  if (!chains) {
    return {
      id: "L18",
      claim,
      status: "not measured",
      value: "",
      evidence: "proving/chains/",
    };
  }
  const { budget } = chains;
  const within =
    chains.programBytes < budget.programBytes &&
    chains.compileMs < budget.compileMs &&
    chains.loadMs < budget.loadMs &&
    chains.transformP99Ms < budget.transformP99Ms;
  const mb = (bytes: number) => `${(bytes / 1_000_000).toFixed(1)} MB`;
  return {
    id: "L18",
    claim,
    status: within ? "met" : "not met",
    value:
      `${chains.shape.steps} steps, ${chains.shape.operations} operations: ` +
      `program ${mb(chains.programBytes)} (budget ${mb(budget.programBytes)}), ` +
      `compile ${chains.compileMs} ms, load ${chains.loadMs} ms (budget ${budget.loadMs}), ` +
      `p99 transform ${chains.transformP99Ms} ms (budget ${budget.transformP99Ms})`,
    evidence: "proving/chains/results.json, asserted by proving/chains/chains.test.ts",
  };
}

export function render(lines: readonly Line[]): string {
  const met = lines.filter((line) => line.status === "met").length;
  const measured = lines.filter((line) => line.status !== "not measured").length;
  return [
    "# Scoreboard",
    "",
    "The launch gate, measured by the proving ground. Generated by",
    "`node --import tsx proving/scoreboard.mts` and regenerated every night.",
    "",
    `${met} of ${lines.length} lines met; ${measured} measured.`,
    "",
    "| Line | Claim | Status | Value | Evidence |",
    "|---|---|---|---|---|",
    ...lines.map(
      (line) =>
        `| ${line.id} | ${line.claim} | ${line.status} | ${line.value.replaceAll("|", "\\|")} | ${line.evidence} |`,
    ),
    "",
  ].join("\n");
}

if (process.argv[1]?.endsWith("scoreboard.mts")) {
  // Only recorded results: a partial run on someone's machine is not the gate.
  const servers = read<ServerResult[]>("proving/servers/results.json");
  const lines = scoreboard({
    corpus: read<CorpusResult[]>("proving/corpus/results.json"),
    manifestPairs: read<{ pairs: { provider: string }[] }>("proving/corpus/manifest.json")
      ?.pairs,
    traffic: read<TrafficResult[]>("proving/traffic/results.json"),
    servers,
    replay: read<ReplayIndex>("proving/replay/index.json"),
    replayed: read<ReplayResult[]>("proving/replay/results.json"),
    fuzz: process.env["FUZZ_RESULT"],
    chains: read<ChainCost & { budget: typeof BUDGET }>("proving/chains/results.json"),
    vectors: read<VectorCounts>("conformance/vectors.json"),
    ownership: existsSync(join(ROOT, "eval/ownership.yaml"))
      ? (parseDocumentText(
          "ownership.yaml",
          readFileSync(join(ROOT, "eval/ownership.yaml"), "utf8"),
        ) as Ownership)
      : undefined,
    overhead: read<OverheadResult & { budget: typeof OVERHEAD_BUDGET }>(
      "proving/overhead/results.json",
    ),
  });
  const page = render(lines);
  await writeFile(join(ROOT, "proving/SCOREBOARD.md"), page, "utf8");
  process.stdout.write(page);
}
