/**
 * The launch gate, measured.
 *
 * Every line of the gate in the production plan, with the value the rigs last
 * measured and the evidence it came from. A line nothing measures yet says so
 * rather than being left out, because a scoreboard that only lists what is
 * going well is a brochure. Regenerated by the nightly proving run; the same
 * page is the public evidence page once the product launches.
 *
 *   node --import tsx proving/scoreboard.mts
 */
import { existsSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { catalogueEntry, isUnclassified } from "@invariant/diff";
import type { PairResult as CorpusResult } from "@invariant/eval";
import { ROOT } from "./corpus/manifest.mts";
import type { ReplayIndex } from "./replay/mine.mts";
import type { PairResult as ServerResult } from "./servers/run.mts";
import type { TrafficResult } from "./traffic/run.mts";

type Status = "met" | "not met" | "not measured";

interface Line {
  id: string;
  claim: string;
  status: Status;
  value: string;
  evidence: string;
}

function read<T>(path: string): T | undefined {
  const full = join(ROOT, path);
  return existsSync(full) ? (JSON.parse(readFileSync(full, "utf8")) as T) : undefined;
}

const percent = (part: number, whole: number) =>
  whole === 0 ? "n/a" : `${((part / whole) * 100).toFixed(1)}%`;

export function scoreboard(inputs: {
  corpus: CorpusResult[] | undefined;
  manifestPairs: { provider: string }[] | undefined;
  traffic: TrafficResult[] | undefined;
  servers: ServerResult[] | undefined;
  replay: ReplayIndex | undefined;
  fuzz: string | undefined;
}): Line[] {
  const lines: Line[] = [];
  const unmeasured = (id: string, claim: string, why: string): Line => ({
    id,
    claim,
    status: "not measured",
    value: "",
    evidence: why,
  });

  lines.push({
    id: "L1",
    claim: "The gate never passes a release whose Changes cannot all be served.",
    status: "met",
    value:
      "Changes generated from the IR's own schema either compile to work for every op or are blocked; every op x location x direction cell is decided and executed",
    evidence:
      "packages/compiler/src/servable.test.ts and packages/compiler/matrix.json, on every commit and deeply every night",
  });

  const corpus = inputs.corpus ?? [];
  const providers = new Set((inputs.manifestPairs ?? []).map((pair) => pair.provider));
  const failing = corpus.filter((result) => result.compileIssues.length > 0);
  const bigEnough = corpus.length >= 1500 && providers.size >= 30;
  lines.push({
    id: "L2",
    claim:
      "Zero drafts that fail to compile, over at least 1500 pairs from 30 providers.",
    status:
      corpus.length === 0
        ? "not measured"
        : failing.length === 0 && bigEnough
          ? "met"
          : "not met",
    value: `${failing.length} pairs with drafts that do not compile, of ${corpus.length} pairs from ${providers.size} providers`,
    evidence: "proving/corpus/results.json (rules judge)",
  });

  // Every id the pinned differ can print is classified; the catalogue's own
  // test asks the binary on every commit. What the corpus shows is how many
  // of the kinds real providers produce are served today.
  const kinds = [
    ...new Set(corpus.flatMap((result) => Object.keys(result.breakingKinds ?? {}))),
  ];
  const unclassified = kinds.filter((kind) => isUnclassified(kind));
  const servedKinds = kinds.filter((kind) => catalogueEntry(kind).served === "yes");
  lines.push({
    id: "L3",
    claim: "Every breaking-change id the pinned differ reports is catalogued.",
    status: unclassified.length === 0 ? "met" : "not met",
    value: `every breaking check the pinned differ knows is classified; of the ${kinds.length} kinds real providers produced, ${unclassified.length} unclassified and ${servedKinds.length} served today`,
    evidence:
      "packages/diff/src/catalogue.ts, checked against the binary on every commit",
  });

  const done = corpus.filter((result) => result.reached === "done");
  const aligned = done.reduce((sum, result) => sum + result.breakingAligned, 0);
  const after = done.reduce((sum, result) => sum + result.breakingAfter, 0);
  const breakingPairs = done.filter((result) => result.breakingAligned > 0);
  const closed = breakingPairs.filter((result) => result.breakingAfter === 0);
  const explained = aligned === 0 ? 0 : (aligned - after) / aligned;
  // The same closure with every open decision answered synthetically: what a
  // provider who answered them would reach. A pair recorded before the corpus
  // measured it counts as it stood without decisions.
  const decided = done.reduce(
    (sum, result) => sum + (result.breakingAfterDecided ?? result.breakingAfter),
    0,
  );
  const measuredDecided = done.filter(
    (result) => result.breakingAfterDecided !== undefined,
  ).length;
  const closedDecided = breakingPairs.filter(
    (result) => (result.breakingAfterDecided ?? result.breakingAfter) === 0,
  );
  // Per place: a shared schema's one change counts once, however many
  // operations return it. The gate is judged on this where it is measured.
  const placed = done.filter((result) => result.places !== undefined);
  const placeSum = (pick: (places: NonNullable<CorpusResult["places"]>) => number) =>
    placed.reduce(
      (sum, result) => sum + pick(result.places as NonNullable<CorpusResult["places"]>),
      0,
    );
  const placesAligned = placeSum((places) => places.aligned);
  const placesAfter = placeSum((places) => places.after);
  const placesDecided = placeSum((places) => places.decided ?? places.after);
  const byPlace = placed.length > 0;
  const headline = byPlace
    ? placesAligned === 0
      ? 1
      : (placesAligned - placesAfter) / placesAligned
    : explained;
  lines.push({
    id: "L4",
    claim:
      "At least 95% of breaking deltas explained, and at least 80% of breaking pairs closed.",
    status:
      corpus.length === 0
        ? "not measured"
        : headline >= 0.95 && closed.length >= 0.8 * breakingPairs.length
          ? "met"
          : "not met",
    value:
      (byPlace
        ? `Per place, on ${placed.length} of ${done.length} completed pairs: ${percent(placesAligned - placesAfter, placesAligned)} of breaking deltas explained, ${percent(placesAligned - placesDecided, placesAligned)} with every open decision answered synthetically. `
        : "") +
      `Per instance: ${percent(aligned - after, aligned)} explained, ${percent(aligned - decided, aligned)} with synthetic answers (measured on ${measuredDecided} pairs). ` +
      `${closed.length} of ${breakingPairs.length} breaking pairs closed (${percent(closed.length, breakingPairs.length)}), ${closedDecided.length} with synthetic answers (${percent(closedDecided.length, breakingPairs.length)}).`,
    evidence:
      "proving/corpus/results.json (rules judge; without decisions, and with synthetic answers)",
  });
  lines.push(
    unmeasured(
      "L4b",
      "Judge precision of at least 99% per family, and no semantically wrong Change surviving the gate.",
      "Needs the S2 judge (M2.2) and the labelled corpus (M3.10).",
    ),
  );
  lines.push(
    unmeasured(
      "L5",
      "Official Stripe SDK suites pass through the proxy against stripe-mock on the new specification.",
      "Consecutive Stripe specifications differ only by enum values added within an API version, which nothing drafts until M3.8 and the judge; the rig would prove nothing yet.",
    ),
  );

  const traffic = inputs.traffic ?? [];
  const sites = traffic.flatMap((result) => result.sites);
  const violating = sites.filter((site) => site.violations > 0);
  const served = sites.filter((site) => !site.retired && site.samples > site.rigFaults);
  const proving = served.filter((site) => site.brokenWithout > 0);
  lines.push({
    id: "L6",
    claim:
      "For every closing pair, at least 100 requests per adapted site through the proxy with zero violations, judged independently.",
    status:
      traffic.length === 0 ? "not measured" : violating.length === 0 ? "met" : "not met",
    value: `${violating.length} sites with violations across ${traffic.length} closing pairs; ${sites.length - served.length} retired sites and ${served.length} served sites (${proving.length} non-vacuous)`,
    evidence: "proving/traffic/results.json",
  });

  const servers = inputs.servers ?? [];
  const projects = new Set(servers.map((result) => result.project));
  const languages = new Set(servers.map((result) => result.language));
  const regressions = servers.reduce((sum, result) => sum + result.regressions.length, 0);
  const broken = servers.reduce((sum, result) => sum + result.broken.length, 0);
  const fixed = servers.reduce((sum, result) => sum + result.served.length, 0);
  lines.push({
    id: "L7",
    claim:
      "At least 6 real servers in 4 language families, across a breaking release of their own, with the old release's suite passing through the proxy.",
    status:
      servers.length === 0
        ? "not measured"
        : projects.size >= 6 &&
            languages.size >= 4 &&
            regressions === 0 &&
            fixed === broken
          ? "met"
          : "not met",
    value: `${projects.size} projects in ${languages.size} languages; ${fixed} of ${broken} tests the releases broke served, ${regressions} regressions`,
    evidence: "proving/servers/results.json",
  });

  const cases = inputs.replay?.cases ?? [];
  const count = (ecosystem: string) =>
    cases.filter((entry) => entry.ecosystem === ecosystem).length;
  lines.push({
    id: "L8",
    claim:
      "Migration replay on at least 50 human migrations each for TypeScript, Python and Go, and 25 for JavaScript: 90% handled, no wrong edits.",
    status: "not measured",
    value: `${cases.length} cases mined (npm ${count("npm")}, pypi ${count("pypi")}, go ${count("go")}); replay not built`,
    evidence: "proving/replay/index.json; replay follows M6",
  });

  lines.push(
    unmeasured(
      "L9",
      "npx init to a blocking check on a scratch pull request, p95 under 10 minutes on Linux, macOS and Windows.",
      "The install test passes on all three from a local registry on every commit; the timed walk from real npm needs the first publish.",
    ),
    unmeasured(
      "L10",
      "In-process adapters for every major Node framework pass one suite.",
      "Hono only (M4.3).",
    ),
    unmeasured("L10b", "A Go net/http adapter passes the same suite.", "M4.9."),
    unmeasured("L11", "A 24-hour proxy soak under chaos with zero violations.", "M10.4."),
    unmeasured("L12", "The Go engine passes every conformance vector.", "M4.9."),
    unmeasured(
      "L13",
      "The whole product journey in a browser against staging.",
      "M7 and M8.",
    ),
    unmeasured("L14", "Enterprise identity, audit, self-hosting and residency.", "M9."),
  );
  lines.push({
    id: "L15",
    claim:
      "Threat-model tests, nightly fuzzers with no open crashers, SBOM and provenance, a clean secrets scan and a recent restore drill.",
    status: "not met",
    value: `nightly fuzzers ${inputs.fuzz === "success" ? "passing" : inputs.fuzz === undefined ? "not run here" : `failing (${inputs.fuzz})`}; the rest is M10`,
    evidence: "proving/fuzz/",
  });
  lines.push(
    unmeasured("L16", "Docs complete, tested from manifests.", "M8.4."),
    unmeasured(
      "L17",
      "Older runtimes either run newer programs or refuse with a typed error.",
      "M3.17.",
    ),
    unmeasured(
      "L18",
      "A 50-step chain over a Stripe-sized spec within stated budgets.",
      "M3.16.",
    ),
    unmeasured("L19", "Proxy p99 overhead asserted in CI.", "M4.10."),
  );
  return lines;
}

export function render(lines: readonly Line[]): string {
  const met = lines.filter((line) => line.status === "met").length;
  const measured = lines.filter((line) => line.status !== "not measured").length;
  return [
    "# Scoreboard",
    "",
    "The launch gate, measured by the proving ground. Generated by",
    "`node --import tsx proving/scoreboard.mts` and regenerated every night.",
    "",
    `${met} of ${lines.length} lines met; ${measured} measured.`,
    "",
    "| Line | Claim | Status | Value | Evidence |",
    "|---|---|---|---|---|",
    ...lines.map(
      (line) =>
        `| ${line.id} | ${line.claim} | ${line.status} | ${line.value.replaceAll("|", "\\|")} | ${line.evidence} |`,
    ),
    "",
  ].join("\n");
}

if (process.argv[1]?.endsWith("scoreboard.mts")) {
  // Only recorded results: a partial run on someone's machine is not the gate.
  const servers = read<ServerResult[]>("proving/servers/results.json");
  const lines = scoreboard({
    corpus: read<CorpusResult[]>("proving/corpus/results.json"),
    manifestPairs: read<{ pairs: { provider: string }[] }>("proving/corpus/manifest.json")
      ?.pairs,
    traffic: read<TrafficResult[]>("proving/traffic/results.json"),
    servers,
    replay: read<ReplayIndex>("proving/replay/index.json"),
    fuzz: process.env["FUZZ_RESULT"],
  });
  const page = render(lines);
  await writeFile(join(ROOT, "proving/SCOREBOARD.md"), page, "utf8");
  process.stdout.write(page);
}
