/**
 * The launch gate, measured.
 *
 * Every line of the gate in the production plan, with the value the rigs last
 * measured and the evidence it came from. A line nothing measures yet says so
 * rather than being left out, because a scoreboard that only lists what is
 * going well is a brochure. Regenerated by the nightly proving run; the same
 * page is the public evidence page once the product launches.
 *
 *   node --import tsx proving/scoreboard.mts
 */
import { existsSync, readFileSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { catalogueEntry, isUnclassified } from "@invariant-app/diff";
import type { PairResult as CorpusResult, Measurement } from "@invariant-app/eval";
import type { BUDGET, ChainCost } from "./chains/cost.ts";
import { ROOT } from "./corpus/manifest.mts";
import { type JourneySummary, met as journeyMet } from "./journey/summary.ts";
import type { BUDGET as OVERHEAD_BUDGET, OverheadResult } from "./overhead/overhead.ts";
import type { ReleaseResults } from "./releases/verify.mts";
import { type AuditFile, agreement } from "./replay/audit.mts";
import type { SiteClass } from "./replay/classify.mts";
import type { ReplayIndex } from "./replay/mine.mts";
import type { ReplayResult } from "./replay/run.mts";
import {
  closureHeadline,
  type PairResult as ServerResult,
  headline as serversHeadline,
  tally,
} from "./servers/pairs.ts";
import type { SkewResult } from "./skew/run.mts";
import {
  judge as judgeSoak,
  BUDGET as SOAK_BUDGET,
  type SoakResults,
} from "./soak/plan.ts";
import {
  type StripeResults,
  headline as stripeHeadline,
  met as stripeMet,
  tally as stripeTally,
} from "./stripe/summary.ts";
import { summarize as summarizeThreats, type ThreatManifest } from "./threats/summary.ts";
import type { TrafficResult } from "./traffic/run.mts";

type Status = "met" | "not met" | "not measured";

interface Line {
  id: string;
  claim: string;
  status: Status;
  value: string;
  evidence: string;
}

/**
 * The most of the L4 denominator that behavior-only places may make up. The
 * class is the catalogue's, by rule, and the share is published beside it.
 */
export const BEHAVIOR_ONLY_CAP = 0.05;

/** The share of breaking places L4 asks to be explained once decisions are answered. */
export const L4_BAR = 0.9;

/** The sections of the conformance vector file, counted. */
export interface VectorCounts {
  vectors: unknown[];
  envelopes: unknown[];
  forms: unknown[];
  xml?: unknown[];
}

function read<T>(path: string): T | undefined {
  const full = join(ROOT, path);
  return existsSync(full) ? (JSON.parse(readFileSync(full, "utf8")) as T) : undefined;
}

/**
 * Forced sites a language needs before its L8 rate counts: below it, one site
 * moves the rate by more than three points, so the rate says little either way.
 */
const L8_MIN_FORCED = 30;
/** The human migrations each language must be replayed on, as L8 states them. */
const L8_MIN_CASES: Record<string, number> = {
  typescript: 50,
  javascript: 25,
  python: 50,
  go: 50,
};

const percent = (part: number, whole: number) =>
  whole === 0 ? "n/a" : `${((part / whole) * 100).toFixed(1)}%`;

export function scoreboard(inputs: {
  corpus: CorpusResult[] | undefined;
  manifestPairs: { provider: string }[] | undefined;
  traffic: TrafficResult[] | undefined;
  servers: ServerResult[] | undefined;
  replay: ReplayIndex | undefined;
  replayed?: ReplayResult[] | undefined;
  audit?: AuditFile | undefined;
  classes?: Record<string, { class: SiteClass }> | undefined;
  fuzz: string | undefined;
  /** The threat-model record, and how its tests last ran. */
  threats?: ThreatManifest | undefined;
  threatsResult?: string | undefined;
  /** What the latest release's artifacts were found to carry. */
  releases?: ReleaseResults | undefined;
  chains?: (ChainCost & { budget: typeof BUDGET }) | undefined;
  overhead?: (OverheadResult & { budget: typeof OVERHEAD_BUDGET }) | undefined;
  vectors?: VectorCounts | undefined;
  judges?: JudgeResults | undefined;
  journey?: JourneySummary | undefined;
  skew?: SkewResult | undefined;
  soak?: SoakResults | undefined;
  stripe?: StripeResults | undefined;
}): Line[] {
  const lines: Line[] = [];
  const unmeasured = (id: string, claim: string, why: string): Line => ({
    id,
    claim,
    status: "not measured",
    value: "",
    evidence: why,
  });

  lines.push({
    id: "L1",
    claim: "The gate never passes a release whose Changes cannot all be served.",
    status: "met",
    value:
      "Changes generated from the IR's own schema either compile to work for every op or are blocked; every op x location x direction cell is decided and executed",
    evidence:
      "packages/compiler/src/servable.test.ts and packages/compiler/matrix.json, on every commit and deeply every night",
  });

  const corpus = inputs.corpus ?? [];
  const providers = new Set((inputs.manifestPairs ?? []).map((pair) => pair.provider));
  const failing = corpus.filter((result) => result.compileIssues.length > 0);
  const bigEnough = corpus.length >= 1500 && providers.size >= 30;
  lines.push({
    id: "L2",
    claim:
      "Zero drafts that fail to compile, over at least 1500 pairs from 30 providers.",
    status:
      corpus.length === 0
        ? "not measured"
        : failing.length === 0 && bigEnough
          ? "met"
          : "not met",
    value: `${failing.length} pairs with drafts that do not compile, of ${corpus.length} pairs from ${providers.size} providers`,
    evidence: "proving/corpus/results.json (rules judge)",
  });

  // Every id the pinned differ can print is classified; the catalogue's own
  // test asks the binary on every commit. What the corpus shows is how many
  // of the kinds real providers produce are served today.
  const kinds = [
    ...new Set(corpus.flatMap((result) => Object.keys(result.breakingKinds ?? {}))),
  ];
  const unclassified = kinds.filter((kind) => isUnclassified(kind));
  const servedKinds = kinds.filter((kind) => catalogueEntry(kind).served === "yes");
  lines.push({
    id: "L3",
    claim: "Every breaking-change id the pinned differ reports is catalogued.",
    status: unclassified.length === 0 ? "met" : "not met",
    value: `every breaking check the pinned differ knows is classified; of the ${kinds.length} kinds real providers produced, ${unclassified.length} unclassified and ${servedKinds.length} served today`,
    evidence:
      "packages/diff/src/catalogue.ts, checked against the binary on every commit",
  });

  const done = corpus.filter((result) => result.reached === "done");
  const aligned = done.reduce((sum, result) => sum + result.breakingAligned, 0);
  const after = done.reduce((sum, result) => sum + result.breakingAfter, 0);
  const breakingPairs = done.filter((result) => result.breakingAligned > 0);
  const closed = breakingPairs.filter((result) => result.breakingAfter === 0);
  // The same closure with every open decision answered synthetically: what a
  // provider who answered them would reach. A pair recorded before the corpus
  // measured it counts as it stood without decisions.
  const decided = done.reduce(
    (sum, result) => sum + (result.breakingAfterDecided ?? result.breakingAfter),
    0,
  );
  const explainedDecided = aligned === 0 ? 0 : (aligned - decided) / aligned;
  const measuredDecided = done.filter(
    (result) => result.breakingAfterDecided !== undefined,
  ).length;
  const closedDecided = breakingPairs.filter(
    (result) => (result.breakingAfterDecided ?? result.breakingAfter) === 0,
  );
  // Per place: a shared schema's one change counts once, however many
  // operations return it. The gate is judged on this where it is measured.
  const placed = done.filter((result) => result.places !== undefined);
  const placeSum = (pick: (places: NonNullable<CorpusResult["places"]>) => number) =>
    placed.reduce(
      (sum, result) => sum + pick(result.places as NonNullable<CorpusResult["places"]>),
      0,
    );
  const placesAligned = placeSum((places) => places.aligned);
  // A break the catalogue classes behavior-only is explained by declaring a
  // `behavior` flag rather than by a transform, so it counts as explained, up
  // to a cap: the class is assigned by rule, and a gate that could be met by
  // calling things behavior-only would measure nothing.
  const behaviorCap = Math.floor(placesAligned * BEHAVIOR_ONLY_CAP);
  const behaviorOnly = placeSum((places) => places.behaviorOnly ?? 0);
  const behaviorOnlyDecided = placeSum(
    (places) => places.behaviorOnlyDecided ?? places.behaviorOnly ?? 0,
  );
  const placesAfter =
    placeSum((places) => places.after) - Math.min(behaviorOnly, behaviorCap);
  const placesDecided =
    placeSum((places) => places.decided ?? places.after) -
    Math.min(behaviorOnlyDecided, behaviorCap);
  const byPlace = placed.length > 0;
  // A pair whose only open places are behavior-only, which the product answers
  // with a declared `behavior` flag rather than a transform, is closed the way
  // the per-place clause counts those places: as explained, and within the same
  // cap on how much of the corpus may be explained so. 43 pairs had nothing
  // else left, request narrowings and authentication changes no adapter can
  // serve, and could never close by any Change. Admitted smallest first, and
  // printed apart, so the line says how many pairs close only by declaration.
  const warningOnly = breakingPairs
    .filter(
      (result) =>
        (result.breakingAfterDecided ?? result.breakingAfter) > 0 &&
        result.places !== undefined &&
        (result.places.decided ?? result.places.after) > 0 &&
        (result.places.decided ?? result.places.after) ===
          (result.places.behaviorOnlyDecided ?? result.places.behaviorOnly ?? 0),
    )
    .sort(
      (a, b) =>
        (a.places?.behaviorOnlyDecided ?? 0) - (b.places?.behaviorOnlyDecided ?? 0),
    );
  let declaredPlaces = 0;
  const closedByDeclaration = warningOnly.filter((result) => {
    const places = result.places?.behaviorOnlyDecided ?? result.places?.behaviorOnly ?? 0;
    if (declaredPlaces + places > behaviorCap) return false;
    declaredPlaces += places;
    return true;
  });
  const pairsClosed = closedDecided.length + closedByDeclaration.length;
  // Judged with every open decision answered: a provider answers them, and
  // many changes cannot be explained without one (which value a new one is
  // shown as, what a field that may now be missing is given). Without them
  // no real API reaches the bar; both numbers are published.
  const headline = byPlace
    ? placesAligned === 0
      ? 1
      : (placesAligned - placesDecided) / placesAligned
    : explainedDecided;
  lines.push({
    id: "L4",
    claim: `At least ${percent(L4_BAR, 1)} of breaking deltas explained once decisions are answered, and at least 80% of breaking pairs closed.`,
    status:
      corpus.length === 0
        ? "not measured"
        : headline >= L4_BAR && pairsClosed >= 0.8 * breakingPairs.length
          ? "met"
          : "not met",
    value:
      (byPlace
        ? `Per place, on ${placed.length} of ${done.length} completed pairs: ${percent(placesAligned - placesAfter, placesAligned)} of breaking deltas explained, ${percent(placesAligned - placesDecided, placesAligned)} with every open decision answered synthetically; behavior-only by catalogue rule ${percent(Math.min(behaviorOnly, behaviorCap), placesAligned)} of places (cap ${percent(BEHAVIOR_ONLY_CAP, 1)}). `
        : "") +
      `Per instance: ${percent(aligned - after, aligned)} explained, ${percent(aligned - decided, aligned)} with synthetic answers (measured on ${measuredDecided} pairs). ` +
      `${closed.length} of ${breakingPairs.length} breaking pairs closed (${percent(closed.length, breakingPairs.length)}), ${closedDecided.length} with synthetic answers (${percent(closedDecided.length, breakingPairs.length)}), ${pairsClosed} (${percent(pairsClosed, breakingPairs.length)}) counting the ${closedByDeclaration.length} whose only open places are behavior-only, declared rather than served, within the cap.`,
    evidence:
      "proving/corpus/results.json (rules judge; without decisions, and with synthetic answers)",
  });
  lines.push(judgeLine(inputs.judges, inputs.servers));
  lines.push(stripeLine(inputs.stripe));

  const traffic = inputs.traffic ?? [];
  const sites = traffic.flatMap((result) => result.sites);
  const violating = sites.filter((site) => site.violations > 0);
  const served = sites.filter((site) => !site.retired && site.samples > site.rigFaults);
  const proving = served.filter((site) => site.brokenWithout > 0);
  lines.push({
    id: "L6",
    claim:
      "For every closing pair, at least 100 requests per adapted site through the proxy with zero violations, judged independently.",
    status:
      traffic.length === 0 ? "not measured" : violating.length === 0 ? "met" : "not met",
    value: `${violating.length} sites with violations across ${traffic.length} closing pairs; ${sites.length - served.length} retired sites and ${served.length} served sites (${proving.length} non-vacuous)`,
    evidence: "proving/traffic/results.json",
  });

  const servers = inputs.servers ?? [];
  const counted = tally(servers);
  lines.push({
    id: "L7",
    claim:
      "At least 6 real servers in 4 language families, across a breaking release of their own, with the old release's suite passing through the proxy.",
    status:
      servers.length === 0
        ? "not measured"
        : counted.proven.length >= 6 &&
            counted.languages.length >= 4 &&
            counted.regressions === 0
          ? "met"
          : "not met",
    value: serversHeadline(counted),
    evidence: "proving/servers/results.json",
  });

  const cases = inputs.replay?.cases ?? [];
  const replayed = (inputs.replayed ?? []).filter((entry) => entry.error === undefined);
  const failed = (inputs.replayed ?? []).filter((entry) => entry.error !== undefined);
  const count = (ecosystem: string) =>
    cases.filter((entry) => entry.ecosystem === ecosystem).length;
  const languages = ["typescript", "javascript", "python", "go"] as const;
  const l8 = languages.map((language) => {
    const mine = replayed.filter((entry) => entry.language === language);

    if (mine.length === 0)
      return {
        language,
        text: `${language} none`,
        enough: false,
        forced: 0,
        forcedHandled: 0,
        differs: 0,
      };
    const sum = (pick: (entry: ReplayResult) => number) =>
      mine.reduce((total, entry) => total + pick(entry), 0);
    const sites = sum((entry) => entry.sites);
    const inScope = sum((entry) => entry.inScope?.sites ?? 0);
    const identical = sum((entry) => entry.inScope?.identical ?? 0);
    const flagged = sum((entry) => entry.inScope?.flagged ?? 0);
    const differs = sum((entry) => entry.inScope?.differs ?? 0);
    const extraFlags = sum((entry) => entry.extraFlags ?? 0);
    const unclassified = sum((entry) => entry.inScope?.unclassified ?? entry.sites);
    // A site the judge could not settle counts as neither, and the
    // rate is given again as if each were a contract change left
    // unhandled, so a classifier that grows more unsure cannot make
    // the headline look better than the worst it could be.
    const contested = sum((entry) => entry.inScope?.contested ?? 0);
    // New files and helpers the humans wrote, which are no sites.
    const newCode = sum((entry) => entry.newCode ?? 0);
    // Every site, the SDK's own changes included, which L8 does not
    // count but a person upgrading does.
    const everywhere = sum((entry) => entry.identical + entry.flagged);
    // The forced sites, over the cases whose two contracts are known.
    const judged = sum((entry) => (entry.inScope?.forced ? entry.inScope.sites : 0));
    const forced = sum((entry) => entry.inScope?.forced?.sites ?? 0);
    const forcedHandled = sum(
      (entry) =>
        (entry.inScope?.forced?.identical ?? 0) + (entry.inScope?.forced?.flagged ?? 0),
    );
    const forcedLine = `forced: ${forced} of ${judged} contract sites in judged cases, ${forcedHandled} handled (${percent(forcedHandled, forced)}), ${inScope - judged} in cases not judged; `;
    return {
      language,
      text: `${language} ${mine.length} cases: of ${sites - newCode} human sites, ${inScope} follow from a contract change; ${identical + flagged} handled (${percent(identical + flagged, inScope)}: ${identical} identical, ${flagged} flagged for a person${contested > 0 ? `; ${percent(identical + flagged, inScope + contested)} at worst, were every contested site a contract change nothing handled` : ""}), ${differs} to adjudicate; ${forcedLine}${newCode} new code written, counted apart; ${extraFlags} flags where no human changed anything; ${contested} contested and ${unclassified} not yet classed, counted as neither; over every human site, the SDK's own changes included, ${everywhere} handled (${percent(everywhere, sites - newCode)})`,
      enough: mine.length >= (L8_MIN_CASES[language] ?? 50),
      forced,
      forcedHandled,
      differs,
    };
  });
  // Judged by engine: JavaScript is read by the TypeScript compiler, so the
  // two are pooled, and each engine needs its forced sites before its rate
  // counts at all.
  const engines = [
    { name: "TypeScript and JavaScript", languages: ["typescript", "javascript"] },
    { name: "Python", languages: ["python"] },
    { name: "Go", languages: ["go"] },
  ].map((engine) => {
    const mine = l8.filter((each) => engine.languages.includes(each.language));
    const forced = mine.reduce((total, each) => total + each.forced, 0);
    const handled = mine.reduce((total, each) => total + each.forcedHandled, 0);
    const differs = mine.reduce((total, each) => total + each.differs, 0);
    return {
      text:
        forced < L8_MIN_FORCED
          ? `${engine.name}: sample too small, ${forced} of the ${L8_MIN_FORCED} forced sites a rate needs to count (${handled} handled)`
          : `${engine.name}: ${handled} of ${forced} forced sites handled (${percent(handled, forced)})`,
      meets: forced >= L8_MIN_FORCED && handled >= forced * 0.9 && differs === 0,
    };
  });
  lines.push({
    id: "L8",
    claim:
      "Migration replay on at least 50 human migrations each for TypeScript, Python and Go, and 25 for JavaScript: 90% of the sites the upgrade forced handled, no wrong edits. " +
      "A site is a region of existing code the humans changed because the contract changed. " +
      "One they replaced or restructured around a changed contract element counts as handled where the engine flagged a line inside the hunk they changed, pointing at that element. " +
      "Lines they added with nothing before them that they replace, a new file or a new helper, are no site: they are counted apart per language as new code written, never as handled or missed, and the calls to them they wrote into existing code remain sites, scored as any other. " +
      "A contract site is forced where a line the humans removed or wrote names an element the pinned differ reports broken between the two releases' contracts; one that names nothing broken is a choice made while the old code still worked, such as adopting a new tool version, and is no migration. " +
      `The rate is given over every contract site and over the forced ones, and the rate is judged per engine, TypeScript and JavaScript together since one compiler reads both, each counting only once it has at least ${L8_MIN_FORCED} forced sites, since below that one site moves its rate by more than three points; a case whose two contracts are not both known is not judged, and its sites are counted apart.`,
    status:
      replayed.length === 0
        ? "not measured"
        : l8.every((each) => each.enough) && engines.every((each) => each.meets)
          ? "met"
          : "not met",
    value:
      `${cases.length} cases mined (npm ${count("npm")}, pypi ${count("pypi")}, go ${count("go")}). ` +
      (replayed.length === 0
        ? "Not yet replayed."
        : `By engine: ${engines.map((each) => each.text).join("; ")}. ` +
          `Replayed ${replayed.length}: ${l8.map((each) => each.text).join("; ")}. ` +
          `${failed.length} could not be replayed. ` +
          auditLine(inputs.audit, inputs.classes)),
    evidence: "proving/replay/results.json (run.mts), index.json",
  });

  lines.push(
    journeyLine(inputs.journey),
    {
      id: "L10",
      claim: "In-process adapters for every major Node framework pass one suite.",
      status: "met",
      value:
        "Hono, node:http, Express 4 and 5, Koa, Fastify 4 and 5, NestJS 10, 11 and 12 and Next.js 14, 15 and 16 pass one suite on Node 22 and 24",
      evidence:
        "packages/runtime-node/src/conformance.test.ts (Next.js through a custom server, fixtures/next-app), packages/runtime-hono, in CI on Node 22 and 24",
    },
    {
      id: "L10b",
      claim: "A Go net/http adapter passes the same suite.",
      status: "met",
      value:
        "the Go engine's net/http middleware passes every case of the Node adapter suite, run against a Go server on the same program",
      evidence:
        "packages/runtime-node/src/conformance.test.ts (go net/http), required in CI by INVARIANT_REQUIRE_GO",
    },
    soakLine(inputs.soak),
    {
      id: "L12",
      claim: "The Go engine passes every conformance vector.",
      // The Go tests read every section of the vector file and fail on any
      // vector they do not pass, so the counts are the file's own.
      status: inputs.vectors ? "met" : "not measured",
      value: inputs.vectors
        ? `all ${inputs.vectors.vectors.length} body, ${inputs.vectors.envelopes.length} request-envelope, ${inputs.vectors.forms.length} form and ${inputs.vectors.xml?.length ?? 0} XML vectors pass`
        : "",
      evidence: "engines/go/invariant/vectors_test.go, in CI on every commit",
    },
    {
      id: "L13",
      claim: "The whole product journey in a browser against staging.",
      status: "not met",
      value:
        "every dashboard screen is walked in a real browser against the whole " +
        "service on each commit, at a laptop's and a phone's width, asserting " +
        "what the service holds rather than an empty state; signing up with " +
        "GitHub and paying by card are not yet walked, and neither is staging",
      evidence: "e2e/journey.spec.ts in the service's repository, in its local CI",
    },
    unmeasured("L14", "Enterprise identity, audit, self-hosting and residency.", "M9."),
  );
  lines.push(
    securityLine(inputs.threats, inputs.threatsResult, inputs.fuzz, inputs.releases),
  );
  lines.push(
    {
      id: "L16",
      claim: "Docs complete, tested from manifests.",
      status: "met",
      value:
        "every CLI command and option, invariant.yaml setting (from its schema), runtime error code, adapter and rung, and breaking-change check the pinned differ knows has its page; every link resolves; every TypeScript sample compiles against the packages it uses, every Go sample against the engine, and the proxy's configuration samples are accepted by the proxy",
      evidence: "docs/docs.test.ts and fixtures/docs-samples, on every commit",
    },
    skewLine(inputs.skew),
    chainLine(inputs.chains),
    overheadLine(inputs.overhead),
  );
  return lines;
}

/**
 * What the latest release's artifacts carry, from proving/releases/verify.mts:
 * attested only when every one of them has a CycloneDX bill of materials and
 * provenance, and the image its signature.
 */
function releasesAttested(releases: ReleaseResults | undefined): {
  attested: boolean;
  value: string;
} {
  if (!releases || releases.artifacts.length === 0) {
    return {
      attested: false,
      value: "SBOM and provenance of the latest release not yet checked",
    };
  }
  const missing = releases.artifacts.filter((entry) => entry.problem !== undefined);
  const packages = releases.artifacts.filter((entry) =>
    entry.artifact.startsWith("@"),
  ).length;
  const whole = `the latest release's ${packages} npm package${packages === 1 ? "" : "s"}, the action and the proxy image`;
  if (missing.length === 0) {
    return {
      attested: true,
      value: `${whole} each carry a CycloneDX SBOM and provenance, checked from the registries; the image is signed`,
    };
  }
  return {
    attested: false,
    value:
      `SBOM and provenance checked on ${whole}: missing on ${missing.length} of ${releases.artifacts.length} (` +
      missing
        .map(
          (entry) => `${entry.artifact}@${entry.version.slice(0, 12)}: ${entry.problem}`,
        )
        .join("; ") +
      ")",
  };
}

/** A job's result, as the scoreboard says it. */
const outcome = (result: string | undefined, passing = "passing") =>
  result === "success"
    ? passing
    : result === undefined
      ? "not run here"
      : `failing (${result})`;

function securityLine(
  threats: ThreatManifest | undefined,
  threatsResult: string | undefined,
  fuzz: string | undefined,
  releases: ReleaseResults | undefined,
): Line {
  const attested = releasesAttested(releases);
  const summary = threats ? summarizeThreats(threats) : undefined;
  const modelled = summary
    ? `threat-model tests ${outcome(threatsResult)}: of the ${summary.rows} rows of DESIGN 11.1, ` +
      `${summary.covered} covered here, ${summary.partly} covered here for this repository's part ` +
      `with the rest in the service's repository, ${summary.outOfScope} wholly the service's; ` +
      `${summary.attacks} attack families from M10.1 sent end to end, ` +
      `${summary.found} weaknesses they found fixed` +
      (summary.gaps.length > 0 ? `; not yet built: ${summary.gaps.join(", ")}` : "")
    : "threat-model tests not recorded";
  // Met only when every part is: the tests pass and name nothing unbuilt, the
  // fuzzers pass, and releases carry an SBOM and provenance.
  const met =
    summary !== undefined &&
    threatsResult === "success" &&
    summary.gaps.length === 0 &&
    fuzz === "success" &&
    attested.attested;
  return {
    id: "L15",
    claim:
      "Threat-model tests, nightly fuzzers with no open crashers, SBOM and provenance, a clean secrets scan and a recent restore drill.",
    status: met ? "met" : "not met",
    value:
      `${modelled}; nightly fuzzers ${outcome(fuzz)}; full-history secrets scan on every commit; ` +
      "restore drill 2026-09-22 (RPO 2.1s, RTO 3s, in the service's repository); " +
      attested.value,
    evidence:
      "proving/threats/manifest.json and its tests, on every commit; proving/fuzz/; the secrets job in .github/workflows/ci.yml; proving/releases/results.json (verify.mts), every night",
  };
}

/** How the site classes L8 rests on were checked, and how well they held up. */
function auditLine(
  audit: AuditFile | undefined,
  classes: Record<string, { class: SiteClass }> | undefined,
): string {
  const base =
    "Sites are classed by rule where the text alone decides, otherwise by Jev, with a second question where it was unsure, a third where the two disagreed, and narrow ones about the wire that settle a site the third left contested only outside the contract.";
  if (!audit || !classes) return `${base} The classes are not yet audited.`;
  const result = agreement(classes, audit);
  const per = Object.entries(result.byClass)
    .map(([name, bucket]) => `${name} ${bucket.agreed}/${bucket.labelled}`)
    .join(", ");
  return `${base} On a fixed sample read by ${audit.reader}, ${result.agreed} of ${result.labelled} agree (${percent(result.agreed, result.labelled)}; ${per}).`;
}

/** What `eval/measure.mts` writes to eval/results.json, which L4b reads. */
export type JudgeResults = Measurement;

/** The labelled corpus the plan asks for, and the share of it mined from real deltas. */
const LABELLED_TARGET = 600;
const MINED_SHARE = 0.4;
const PRECISION_TARGET = 0.99;

/** A judge's floors as the line reads them: one number where both are the same. */
function floors(threshold: JudgeResults["judges"][number]["threshold"]): string {
  return threshold.named === threshold.none
    ? String(threshold.named)
    : `${threshold.named} naming a field, ${threshold.none} saying none did`;
}

function judgeLine(
  results: JudgeResults | undefined,
  servers: ServerResult[] | undefined,
): Line {
  const claim =
    "Judge precision of at least 99% per family, and no semantically wrong Change surviving the gate.";
  // The mined labels were read by Claude agents, the family S2 is from, so
  // S2's agreement with them is the figure most likely to flatter; the line
  // says so wherever it is read.
  const evidence =
    "eval/results.json (eval/measure.mts, from recorded answers on every commit), against labels read by Claude agents, the model family S2 is from (eval/mined/labels.json); proving/servers/results.json for false closure";
  if (!results || results.judges.length === 0) {
    return { id: "L4b", claim, status: "not measured", value: "", evidence };
  }
  const { corpus } = results;
  const sized =
    corpus.cases >= LABELLED_TARGET && corpus.mined / corpus.cases >= MINED_SHARE;
  const perJudge = results.judges.map((judge) => {
    const families = Object.entries(judge.byFamily).filter(([, at]) => at.answered > 0);
    const [weakest] = [...families].sort(([, a], [, b]) => a.precision - b.precision);
    const role = judge.judge === "s2" ? ", also the auto-provider" : "";
    const lowest = weakest
      ? `, lowest family ${weakest[0]} ${percent(weakest[1].answered - weakest[1].wrong, weakest[1].answered)} of ${weakest[1].answered}`
      : "";
    const missing = judge.missing > 0 ? `, ${judge.missing} cases unrecorded` : "";
    return {
      precise:
        judge.missing === 0 &&
        judge.overall.answered > 0 &&
        families.every(([, at]) => at.precision >= PRECISION_TARGET),
      text:
        `${judge.judge}${judge.model ? ` (${judge.model}${role})` : ""} at ${floors(judge.threshold)}: ` +
        `${percent(judge.overall.answered - judge.overall.wrong, judge.overall.answered)} on ${judge.overall.answered} answered ` +
        `(mined ${percent(judge.mined.answered - judge.mined.wrong, judge.mined.answered)} on ${judge.mined.answered}), ` +
        `${judge.overall.wrong} wrong${lowest}${missing}`,
    };
  });
  const counts = tally(servers ?? []);
  const closed = counts.comparedAnswers > 0 && counts.wrongSites === 0;
  return {
    id: "L4b",
    claim,
    status:
      sized && perJudge.every((judge) => judge.precise) && closed ? "met" : "not met",
    value:
      `Per family at each judge's drafting threshold: ${perJudge.map((judge) => judge.text).join("; ")}. ` +
      `Labelled corpus ${corpus.cases} cases (target ${LABELLED_TARGET}), ${corpus.mined} mined from real deltas ` +
      `(${percent(corpus.mined, corpus.cases)}, target ${MINED_SHARE * 100}%). ` +
      `False closure on Rig D: ${closureHeadline(counts)}.`,
    evidence,
  };
}

/**
 * L5, from rig B. The primary criteria are the plan's: no request the mock
 * on the new specification refuses with a 400, and no answer the old
 * specification does not allow, through the proxy, over what the old mock on
 * its own specification already showed. Suite-green is reported beside them
 * and decides nothing.
 */
function stripeLine(stripe: StripeResults | undefined): Line {
  const claim =
    "Official Stripe SDK suites pass through the proxy against stripe-mock on the new specification.";
  const evidence = "proving/stripe/results.json";
  if (!stripe || stripe.pairs.length === 0) {
    return { id: "L5", claim, status: "not measured", value: "", evidence };
  }
  const counted = stripeTally(stripe);
  return {
    id: "L5",
    claim,
    status: stripeMet(counted) ? "met" : "not met",
    value: stripeHeadline(counted),
    evidence,
  };
}

function overheadLine(
  overhead: (OverheadResult & { budget: typeof OVERHEAD_BUDGET }) | undefined,
): Line {
  const claim = "Proxy p99 overhead asserted in CI.";
  if (!overhead) {
    return {
      id: "L19",
      claim,
      status: "not measured",
      value: "",
      evidence: "proving/overhead/",
    };
  }
  const { budget } = overhead;
  const errors =
    overhead.direct.errors + overhead.current.errors + overhead.adapted.errors;
  return {
    id: "L19",
    claim,
    status: errors === 0 && overhead.addedP99Ms <= budget.addedP99Ms ? "met" : "not met",
    value:
      `at ${overhead.rps} requests a second of a ${(overhead.bodyBytes / 1024).toFixed(1)} KiB list, every item adapted: ` +
      `${overhead.addedP99Ms} ms added at p99 (budget ${budget.addedP99Ms}); ` +
      `p99 ${overhead.direct.p99Ms} ms direct, ${overhead.current.p99Ms} ms through the proxy for a current caller, ` +
      `${overhead.adapted.p99Ms} ms adapted`,
    evidence:
      "proving/overhead/results.json, asserted by proving/overhead/measure.mts --check in its own CI step",
  };
}

function journeyLine(journey: JourneySummary | undefined): Line {
  const claim =
    "npx init to a blocking check on a scratch pull request, p95 under 10 minutes on Linux, macOS and Windows.";
  if (!journey) {
    return {
      id: "L9",
      claim,
      status: "not measured",
      value: "",
      evidence:
        "proving/journey/, nightly once the scratch provider's credentials are set",
    };
  }
  const minutes = (seconds: number | null) =>
    seconds === null ? "no runs" : `p95 ${(seconds / 60).toFixed(1)} min`;
  const names: Record<string, string> = {
    linux: "Linux",
    darwin: "macOS",
    win32: "Windows",
  };
  return {
    id: "L9",
    claim,
    status: journeyMet(journey) ? "met" : "not met",
    value: Object.entries(journey.systems)
      .map(
        ([os, system]) =>
          `${names[os] ?? os}: ${system.blocked} of ${system.runs} runs blocked, ${minutes(system.p95Seconds)}`,
      )
      .join("; ")
      .concat(
        `; needs ${journey.runsNeeded} runs each under ${journey.budgetSeconds / 60} min`,
      ),
    evidence: "proving/journey/results.json, from real npm to a real pull request",
  };
}

function skewLine(skew: SkewResult | undefined): Line {
  const claim = "Older runtimes either run newer programs or refuse with a typed error.";
  const always =
    "every program states its format, compiler and oldest runtime, and a runtime refuses one it is too old for before reading any of it";
  if (!skew) {
    return {
      id: "L17",
      claim,
      status: "not met",
      value: `${always}; the published runtime has not been run against this commit's programs`,
      evidence: "packages/runtime/src/skew.test.ts; proving/skew/",
    };
  }
  const clean = skew.different.length === 0 && skew.untyped.length === 0;
  return {
    id: "L17",
    claim,
    status: clean ? "met" : "not met",
    value:
      `${always}. The published runtime ${skew.published}, given ${skew.cases} programs from ` +
      `${skew.compiledBy}: ${skew.same} give the same answer, ${skew.refusedAtLoad} refused at load ` +
      `with a typed error, ${skew.different.length} answer differently, ${skew.untyped.length} fail untyped`,
    evidence: "proving/skew/results.json and packages/runtime/src/skew.test.ts",
  };
}

function chainLine(chains: (ChainCost & { budget: typeof BUDGET }) | undefined): Line {
  const claim = "A 50-step chain over a Stripe-sized spec within stated budgets.";
  if (!chains) {
    return {
      id: "L18",
      claim,
      status: "not measured",
      value: "",
      evidence: "proving/chains/",
    };
  }
  const { budget } = chains;
  const within =
    chains.programBytes < budget.programBytes &&
    chains.compileMs < budget.compileMs &&
    chains.loadMs < budget.loadMs &&
    chains.transformP99Ms < budget.transformP99Ms;
  const mb = (bytes: number) => `${(bytes / 1_000_000).toFixed(1)} MB`;
  return {
    id: "L18",
    claim,
    status: within ? "met" : "not met",
    value:
      `${chains.shape.steps} steps, ${chains.shape.operations} operations: ` +
      `program ${mb(chains.programBytes)} (budget ${mb(budget.programBytes)}), ` +
      `compile ${chains.compileMs} ms, load ${chains.loadMs} ms (budget ${budget.loadMs}), ` +
      `p99 transform ${chains.transformP99Ms} ms (budget ${budget.transformP99Ms})`,
    evidence: "proving/chains/results.json, asserted by proving/chains/chains.test.ts",
  };
}

/** L11, from the last recorded soak, with whichever of its criteria it missed. */
function soakLine(soak: SoakResults | undefined): Line {
  const claim = `A ${SOAK_BUDGET.hours}-hour proxy soak at a stated rate under chaos: zero responses failing the old contract, a bounded memory trend, no leaked sockets.`;
  const evidence =
    "proving/soak/results.json, from `node --import tsx proving/soak/soak.mts --record`";
  if (!soak) return { id: "L11", claim, status: "not measured", value: "", evidence };
  // Judged again against the budget as it stands, so a recorded run is held
  // to the line's current statement rather than the one it ran under.
  const verdict = judgeSoak({
    hours: soak.hours,
    rps: soak.rps,
    violations: soak.violations.responses + soak.violations.requests,
    unanswered: soak.transport.otherwise,
    crashes: soak.disturbances.crashes,
    rss: { maxMb: soak.rss.maxMb, trend: soak.rss.trend },
    sockets: {
      leaked:
        soak.sockets.leaked === undefined
          ? undefined
          : soak.sockets.leaked + soak.sockets.upstreamLeftOpen,
    },
  });
  const missed = verdict.criteria.filter((criterion) => !criterion.met);
  const reloads = soak.disturbances.reloads;
  return {
    id: "L11",
    claim,
    status: verdict.met ? "met" : "not met",
    value:
      `${soak.hours} hours at ${soak.rps.achieved} of ${soak.rps.stated} requests a second, ` +
      `${soak.requests.issued} requests: ${soak.violations.responses} responses failing their contract, ` +
      `${soak.violations.requests} requests failing the current one, ${soak.transport.otherwise} unanswered outside a restart; ` +
      `${soak.disturbances.flagFlips} flag flips, ${reloads.written} program reloads (${reloads.broken} that did not load), ` +
      `${soak.disturbances.restarts} restarts, ${soak.disturbances.crashes} crashes; ` +
      `memory ${soak.rss.maxMb} MB at most, ${soak.sockets.leaked ?? "unmeasured"} sockets left open` +
      (missed.length > 0
        ? `. Missed: ${missed.map((criterion) => `${criterion.name} (${criterion.value})`).join("; ")}`
        : ""),
    evidence,
  };
}

export function render(lines: readonly Line[]): string {
  const met = lines.filter((line) => line.status === "met").length;
  const measured = lines.filter((line) => line.status !== "not measured").length;
  return [
    "# Scoreboard",
    "",
    "The launch gate, measured by the proving ground. Generated by",
    "`node --import tsx proving/scoreboard.mts` and regenerated every night.",
    "",
    `${met} of ${lines.length} lines met; ${measured} measured.`,
    "",
    "| Line | Claim | Status | Value | Evidence |",
    "|---|---|---|---|---|",
    ...lines.map(
      (line) =>
        `| ${line.id} | ${line.claim} | ${line.status} | ${line.value.replaceAll("|", "\\|")} | ${line.evidence} |`,
    ),
    "",
  ].join("\n");
}

if (process.argv[1]?.endsWith("scoreboard.mts")) {
  // Only recorded results: a partial run on someone's machine is not the gate.
  const servers = read<ServerResult[]>("proving/servers/results.json");
  const lines = scoreboard({
    corpus: read<CorpusResult[]>("proving/corpus/results.json"),
    manifestPairs: read<{ pairs: { provider: string }[] }>("proving/corpus/manifest.json")
      ?.pairs,
    traffic: read<TrafficResult[]>("proving/traffic/results.json"),
    servers,
    replay: read<ReplayIndex>("proving/replay/index.json"),
    replayed: read<ReplayResult[]>("proving/replay/results.json"),
    audit: read<AuditFile>("proving/replay/audit.json"),
    classes: read<Record<string, { class: SiteClass }>>("proving/replay/classes.json"),
    fuzz: process.env["FUZZ_RESULT"],
    threats: read<ThreatManifest>("proving/threats/manifest.json"),
    threatsResult: process.env["THREATS_RESULT"],
    releases: read<ReleaseResults>("proving/releases/results.json"),
    chains: read<ChainCost & { budget: typeof BUDGET }>("proving/chains/results.json"),
    vectors: read<VectorCounts>("conformance/vectors.json"),
    judges: read<JudgeResults>("eval/results.json"),
    overhead: read<OverheadResult & { budget: typeof OVERHEAD_BUDGET }>(
      "proving/overhead/results.json",
    ),
    journey: read<JourneySummary>("proving/journey/results.json"),
    skew: read<SkewResult>("proving/skew/results.json"),
    soak: read<SoakResults>("proving/soak/results.json"),
    stripe: read<StripeResults>("proving/stripe/results.json"),
  });
  const page = render(lines);
  await writeFile(join(ROOT, "proving/SCOREBOARD.md"), page, "utf8");
  process.stdout.write(page);
}
