/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 45ed8e3b1e33
 */
// #region imports
import { chatComplete } from "../funcs/chatComplete.js";
import { ClientSDK } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";
import { convertToParsedChatCompletionResponse, transformToChatCompletionRequest, } from "../extra/structChat.js";
// #endregion imports
export class Chat extends ClientSDK {
    // #region sdk-class-body
    async parse(request, options) {
        const ccr_request = transformToChatCompletionRequest(request);
        const response = await unwrapAsync(chatComplete(this, ccr_request, options));
        const parsed_response = convertToParsedChatCompletionResponse(response, request.responseFormat);
        return parsed_response;
    }
    // #endregion sdk-class-body
    /**
     * Chat Completion
     */
    async complete(request, options) {
        return unwrapAsync(chatComplete(this, request, options));
    }
}
//# sourceMappingURL=chat.js.map
