// Code generated by mockery. DO NOT EDIT.

package consumer

import (
	"context"

	"example.com/sdk"
)

// MockComments is a mock of Comments.
type MockComments struct {
	Calls int
}

// EditComment records a call.
func (m *MockComments) EditComment(ctx context.Context, owner, repo string, id int64, comment *sdk.IssueComment) error {
	m.Calls++
	return nil
}
